<?php

namespace Database\Seeders;

use App\Enums\BlogCategoryStatus;
use App\Enums\BlogStatus;
use App\Enums\PortfolioCategoryStatus;
use App\Enums\PortfolioStatus;
use App\Enums\ProductStatus;
use App\Enums\ServiceCategoryStatus;
use App\Enums\ServiceStatus;
use App\Models\BlogCategory;
use App\Models\BlogPost;
use App\Models\BlogTag;
use App\Models\PortfolioCategory;
use App\Models\PortfolioProject;
use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\ProductSeo;
use App\Models\Service;
use App\Models\ServiceCategory;
use App\Models\ServiceSeo;
use App\Models\PortfolioProjectSeo;
use App\Models\BlogPostSeo;
use App\Models\User;
use Illuminate\Database\Seeder;

class ProductionDemoContentSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::where('role', 'admin')->firstOrFail();
        $productCategories = $this->categories(ProductCategory::class, ['Business Software', 'SaaS Platforms', 'Commerce Solutions', 'Automation Tools'], ['is_active' => true]);
        $serviceCategories = $this->categories(ServiceCategory::class, ['Software Development', 'Enterprise Solutions', 'Integrations', 'Cloud & DevOps'], ['status' => ServiceCategoryStatus::Published]);
        $portfolioCategories = $this->categories(PortfolioCategory::class, ['Enterprise Software', 'E-Commerce', 'SaaS', 'Business Automation'], ['status' => PortfolioCategoryStatus::Published]);
        $blogCategories = $this->categories(BlogCategory::class, ['Software Development', 'Business Automation', 'Digital Transformation', 'Engineering Insights'], ['status' => BlogCategoryStatus::Published]);

        $media = ['product' => 'demo/media/product-dashboard.png', 'service' => 'demo/media/operations-overview.png', 'portfolio' => 'demo/media/portfolio-platform.png', 'blog' => 'demo/media/knowledge-banner.png'];
        $products = [
            ['NioxERP Business Suite', 'nioxerp-business-suite', $productCategories['Business Software']->id, 'A unified business management platform for finance, sales, inventory, HR, procurement, and operational reporting.', 'NioxERP Business Suite helps growing businesses manage core operations from one connected platform. Designed for teams that have outgrown spreadsheets and disconnected software, it brings finance, inventory, sales, purchasing, human resources, reporting, and administrative workflows into a centralized system. Key capabilities include sales and customer management, inventory control, purchasing, accounting, HR, role-based access, dashboards, reports, and workflow automation.', 1],
            ['NioxCommerce Platform', 'nioxcommerce-platform', $productCategories['Commerce Solutions']->id, 'A scalable commerce platform for products, customers, orders, payments, promotions, and business operations.', 'NioxCommerce Platform provides the foundation for modern digital commerce experiences. It combines customer-facing commerce with practical tools for products, orders, customers, payments, promotions, inventory, and reporting. It is suitable for retail, D2C, B2B commerce, multi-category stores, and specialist marketplaces.', 2],
            ['NioxFlow Automation', 'nioxflow-automation', $productCategories['Automation Tools']->id, 'A workflow automation solution for reducing repetitive work and connecting business processes across teams.', 'NioxFlow Automation turns repetitive operational tasks into structured digital workflows. Teams can standardize approvals, internal requests, notifications, data movement, checklists, and API-triggered processes while improving visibility and accountability.', 3],
        ];
        foreach ($products as [$name, $slug, $category, $short, $full, $order]) {
            $product = Product::withTrashed()->updateOrCreate(['slug' => $slug], ['product_category_id' => $category, 'created_by' => $admin->id, 'updated_by' => $admin->id, 'name' => $name, 'version' => '1.0.0', 'status' => ProductStatus::Published, 'is_featured' => true, 'display_order' => $order, 'short_description' => $short, 'full_description' => $full, 'thumbnail_path' => $media['product'], 'banner_path' => $media['product'], 'published_at' => now()]);
            $product->restore(); ProductSeo::updateOrCreate(['product_id' => $product->id], ['meta_title' => str($name.' | DevNiox')->limit(60, ''), 'meta_description' => str($short)->limit(160, ''), 'is_indexable' => true]);
        }

        $services = [
            ['Custom Software Development', 'custom-software-development', 'Software Development', 'Purpose-built web and business applications engineered around your processes, users, and growth goals.', 'We design and develop custom software for businesses that need more than an off-the-shelf solution. Our approach covers requirements analysis, architecture, UI implementation, backend systems, integrations, testing, and deployment.', 1],
            ['Business Process Automation', 'business-process-automation', 'Enterprise Solutions', 'Digitize repetitive processes and connect teams with reliable automated workflows.', 'We identify repetitive manual processes and transform them into efficient digital workflows. Solutions can connect existing systems, automate approvals, synchronize information, trigger notifications, and reduce unnecessary data entry.', 2],
            ['API & Payment Gateway Integration', 'api-payment-gateway-integration', 'Integrations', 'Securely connect applications with payment gateways, third-party APIs, and essential business services.', 'We integrate applications with payment providers and third-party platforms using secure, maintainable API architecture. Work may include Stripe, PayPal, SSLCommerz, bKash, Nagad, REST APIs, webhooks, CRM, ERP, and SaaS integrations.', 3],
            ['Cloud Deployment & DevOps', 'cloud-deployment-devops', 'Cloud & DevOps', 'Reliable deployment environments, CI/CD workflows, server configuration, and production infrastructure.', 'We help teams move applications from development into stable production infrastructure, including Linux servers, cloud deployment, Docker, CI/CD, web servers, SSL, databases, environment configuration, monitoring preparation, and backup strategy.', 4],
        ];
        foreach ($services as [$name, $slug, $category, $short, $full, $order]) {
            $service = Service::withTrashed()->updateOrCreate(['slug' => $slug], ['service_category_id' => $serviceCategories[$category]->id, 'created_by' => $admin->id, 'updated_by' => $admin->id, 'name' => $name, 'status' => ServiceStatus::Published, 'is_featured' => true, 'display_order' => $order, 'short_description' => $short, 'full_description' => $full, 'cover_image_path' => $media['service'], 'featured_image_path' => $media['service'], 'published_at' => now()]);
            $service->restore(); ServiceSeo::updateOrCreate(['service_id' => $service->id], ['meta_title' => str($name.' | DevNiox')->limit(60, ''), 'meta_description' => str($short)->limit(160, ''), 'is_indexable' => true]);
        }

        $projects = [
            ['Enterprise Operations Management System', 'enterprise-operations-management-system', 'Enterprise Software', 'A centralized operational platform connecting sales, inventory, procurement, finance, and management reporting.', 'We designed a modular enterprise operations platform for a growing business that needed better visibility across departments. The solution centralized sales, inventory, procurement, expenses, user management, dashboards, and reporting while preserving role-specific access.', 1],
            ['Multi-Channel Commerce Platform', 'multi-channel-commerce-platform', 'E-Commerce', 'A responsive commerce platform with catalog management, checkout, payments, orders, and administrative reporting.', 'This commerce solution combines a polished shopping experience with a practical management environment for catalog, categories, filtering, cart, checkout, payments, customers, orders, and reporting.', 2],
            ['Smart QR Restaurant Ordering System', 'smart-qr-restaurant-ordering-system', 'SaaS', 'A QR-based digital ordering platform designed to streamline restaurant ordering and reduce manual service dependency.', 'Guests scan a table QR code, browse a digital menu, customize items, and submit orders from their phones. Administrators manage categories, products, pricing, orders, tables, payment status, and restaurant settings.', 3],
            ['Automated Lead Management Workflow', 'automated-lead-management-workflow', 'Business Automation', 'A structured lead pipeline that automates assignment, status tracking, follow-ups, and management visibility.', 'This workflow solution organizes incoming sales enquiries into a consistent process with lead capture, assignment, status tracking, follow-up scheduling, notes, team visibility, and conversion reporting.', 4],
        ];
        foreach ($projects as [$name, $slug, $category, $short, $full, $order]) {
            $project = PortfolioProject::withTrashed()->updateOrCreate(['slug' => $slug], ['portfolio_category_id' => $portfolioCategories[$category]->id, 'created_by' => $admin->id, 'updated_by' => $admin->id, 'name' => $name, 'client_name' => null, 'industry' => $category, 'completion_date' => now()->subMonths($order), 'status' => PortfolioStatus::Published, 'is_featured' => $order === 1, 'display_order' => $order, 'thumbnail_path' => $media['portfolio'], 'cover_image_path' => $media['portfolio'], 'short_description' => $short, 'full_description' => $full, 'published_at' => now()]);
            $project->restore(); PortfolioProjectSeo::updateOrCreate(['portfolio_project_id' => $project->id], ['meta_title' => str($name.' | DevNiox')->limit(60, ''), 'meta_description' => str($short)->limit(160, ''), 'is_indexable' => true]);
        }

        $tagNames = ['Laravel', 'SaaS', 'Automation', 'ERP', 'API', 'Cloud', 'E-Commerce', 'Digital Transformation'];
        $tags = collect($tagNames)->mapWithKeys(fn ($name) => [$name => BlogTag::firstOrCreate(['slug' => str($name)->slug()], ['name' => $name])]);
        $posts = [
            ['How Business Process Automation Reduces Operational Bottlenecks', 'how-business-process-automation-reduces-operational-bottlenecks', 'Business Automation', 'Manual handoffs, repetitive data entry, and disconnected tools can quietly slow down an organization. Business process automation helps remove those bottlenecks.', 'Operational bottlenecks rarely arrive as one dramatic failure. They appear as repeated handoffs, duplicate data entry, unclear approvals, and reports that arrive after a decision has already been made. Over time, these small delays become a meaningful drag on customer service and team capacity.\n\nAutomation creates value when it gives a process a clear owner, a visible state, and a reliable next step. Approval workflows can route requests to the right people, enforce required information, and record decisions. Data synchronization can keep customer, order, and finance records aligned across systems. Notifications can replace manual status chasing without creating another noisy inbox. Reporting can turn process history into useful operational insight.\n\nThe best automation projects begin with observation rather than technology. Map the current process, identify exceptions, define the desired outcome, and decide where human judgment must remain. Not every process should be automated: unstable rules, rare activities, and decisions that depend on context may become harder to manage when hidden behind rigid automation.\n\nA practical implementation starts with one measurable workflow. Define roles, inputs, states, failure handling, audit requirements, and success measures. Then integrate the systems that already hold authoritative data. Release in increments, monitor adoption, and refine the process with the people who operate it.\n\nBusiness process automation is most effective when it makes work easier to understand, not merely faster to execute. The result is a dependable operating rhythm where teams spend less time moving information and more time acting on it.', ['Automation', 'Digital Transformation']],
            ['Custom Software vs Off-the-Shelf Software: Which Is Right for Your Business?', 'custom-software-vs-off-the-shelf-software', 'Software Development', 'Choosing between custom software and a ready-made product depends on your processes, budget, growth plans, and the importance of flexibility.', 'Off-the-shelf software offers a fast starting point. It can provide proven features, predictable subscription costs, and an established support model. For common workflows, that convenience is often the right business decision.\n\nCustom software takes a different approach: the system is designed around the organization’s rules, users, data, and integrations. That can improve fit and reduce workarounds, but it also requires clearer discovery, deliberate ownership, and an investment in maintenance.\n\nImplementation speed and total cost should be considered together. A ready-made tool may launch quickly, yet configuration, duplicate data, manual reconciliation, and multiple subscriptions can create long-term cost. Custom development may take longer initially, but a focused scope can create a stronger operational foundation.\n\nFlexibility, scalability, security, and integration requirements are especially important. If the process is a competitive differentiator or standard products force costly exceptions, custom software deserves serious evaluation. If the process is common and the business wants minimal operational ownership, a mature product may be preferable.\n\nThe practical answer is rarely ideological. Compare the current workflow, required controls, integration needs, growth assumptions, internal capability, and exit options. Choose the approach that gives the business dependable outcomes and a sustainable path to change.', ['SaaS', 'Digital Transformation']],
            ['What Makes a SaaS Platform Ready to Scale?', 'what-makes-a-saas-platform-ready-to-scale', 'Engineering Insights', 'Scalability is not only about traffic. A SaaS platform also needs maintainable architecture, secure data access, reliable operations, and growing-team support.', 'A SaaS platform is ready to scale when its architecture makes change predictable. Capacity matters, but so do clear boundaries, dependable data ownership, tenant isolation where relevant, and operational visibility.\n\nStart with a database strategy that reflects the product’s access patterns. Indexes, transaction boundaries, retention rules, and migration discipline protect performance as records grow. APIs should have explicit contracts, authentication, validation, rate limits, and useful failure responses.\n\nCaching can reduce repeated work, while queues and background jobs keep slow tasks away from user-facing requests. These tools work best when invalidation, retries, idempotency, and monitoring are treated as first-class design concerns.\n\nSecurity must scale with the product. Apply least privilege, protect sensitive data, log meaningful events, and test authorization paths. Observability should show latency, error rates, job health, storage use, and business-critical flows.\n\nDeployment also needs repeatability. Environment configuration, automated checks, backups, rollback planning, and documented runbooks reduce dependence on one person. A scalable platform is therefore not just a faster application; it is a system a growing team can safely operate and improve.', ['SaaS', 'Cloud', 'API']],
            ['A Practical Guide to Payment Gateway Integration for Web Applications', 'payment-gateway-integration-guide', 'Software Development', 'A reliable payment integration involves more than a checkout page. Transaction state, callbacks, security, and failure handling all matter.', 'Payment integration is a state-management problem as much as a user-interface problem. A typical lifecycle includes checkout creation, customer redirection, provider response, callback handling, verification, and final order reconciliation.\n\nThe application should never treat a browser redirect as proof of payment. Validate signatures where the provider supports them, retrieve authoritative transaction details, and record transitions such as pending, failed, paid, and refunded. Webhooks are valuable because they can confirm events even when a customer closes the browser.\n\nIdempotency protects against duplicate callbacks and repeated requests. Logging should capture correlation identifiers, provider responses, and safe diagnostic context without exposing credentials or payment secrets. Sandbox testing should include declined payments, timeouts, duplicate notifications, partial failures, and delayed confirmations.\n\nThe same principles apply whether the integration uses Stripe, PayPal, SSLCommerz, bKash, or Nagad. The implementation details differ, but secure configuration, clear state transitions, validation, and reconciliation remain essential.\n\nA production-ready integration is one the support team can explain when a customer asks, “What happened to my payment?” Design for that question from the beginning.', ['API', 'E-Commerce']],
        ];
        foreach ($posts as $index => [$title, $slug, $category, $summary, $body, $tagList]) {
            $post = BlogPost::withTrashed()->updateOrCreate(['slug' => $slug], ['blog_category_id' => $blogCategories[$category]->id, 'author_id' => $admin->id, 'updated_by' => $admin->id, 'title' => $title, 'status' => BlogStatus::Published, 'is_featured' => $index === 0, 'published_at' => now()->subDays($index), 'reading_time' => 5, 'display_order' => $index + 1, 'featured_image_path' => $media['blog'], 'social_image_path' => $media['blog'], 'summary' => $summary, 'body' => $body]);
            $post->restore(); $post->tags()->sync($tags->only($tagList)->pluck('id')); BlogPostSeo::updateOrCreate(['blog_post_id' => $post->id], ['meta_title' => str($title.' | DevNiox')->limit(60, ''), 'meta_description' => str($summary)->limit(160, ''), 'is_indexable' => true]);
        }
    }

    private function categories(string $model, array $names, array $defaults): array
    {
        return collect($names)->mapWithKeys(fn ($name, $index) => [$name => $model::firstOrCreate(['slug' => str($name)->slug()], array_merge(['name' => $name, 'description' => $name.' solutions for modern businesses.', 'sort_order' => $index + 1], $defaults))])->all();
    }
}
