@extends('layouts.app')
@section('title','Services')
@section('description','Explore DevNiox professional software and digital services.')
@section('canonical',route('services'))
@section('content')
@php($leadService = $services->first())
<header class="services-hero"><div class="container"><div class="row g-5 align-items-end"><div class="col-lg-7"><p class="eyebrow">Expertise, applied</p><h1>From complex brief to dependable delivery.</h1><p class="services-intro">{{ $leadService?->short_description ?? ($siteSettings['seo.meta_description'] ?? '') }}</p></div><div class="col-lg-5">@if($leadService?->processSteps->isNotEmpty())<ol class="method-preview">@foreach($leadService->processSteps->take(4) as $step)<li><span>{{ str_pad($step->step_number ?: $loop->iteration,2,'0',STR_PAD_LEFT) }}</span><div><strong>{{ $step->title }}</strong><small>{{ Str::limit($step->description,90) }}</small></div></li>@endforeach</ol>@endif</div></div></div></header>
<section class="service-filter-rail"><div class="container"><form method="get" role="search"><label class="visually-hidden" for="service-search">Search services</label><i class="bi bi-search"></i><input id="service-search" name="search" value="{{ request('search') }}" placeholder="Search expertise"><label class="visually-hidden" for="service-category">Category</label><select id="service-category" name="category"><option value="">All disciplines</option>@foreach($categories as $category)<option value="{{ $category->slug }}" @selected(request('category')===$category->slug)>{{ $category->name }} ({{ $category->services_count }})</option>@endforeach</select><button class="btn btn-dark">Find expertise</button></form></div></section>
<section class="service-practice"><div class="container"><div class="practice-heading"><p class="eyebrow">Our practices</p><h2>Specialists around the outcome, not the org chart.</h2></div><div class="practice-list">@forelse($services as $service)<article class="practice-row"><div class="practice-index">{{ str_pad(($services->firstItem() ?? 1)+$loop->index,2,'0',STR_PAD_LEFT) }}</div><div class="practice-summary"><p>{{ $service->category->name }}</p><h3><a href="{{ route('services.show',$service->slug) }}">{{ $service->name }}</a></h3><div>{{ $service->short_description }}</div></div><div class="practice-evidence">@if($service->processSteps->isNotEmpty())<div><span>Workflow</span>@foreach($service->processSteps->take(2) as $step)<small>{{ $step->step_number }}. {{ $step->title }}</small>@endforeach</div>@endif @if($service->deliverables->isNotEmpty())<div><span>Deliverables</span>@foreach($service->deliverables->take(3) as $deliverable)<small>{{ $deliverable->title }}</small>@endforeach</div>@endif @if($service->technologies->isNotEmpty())<div><span>Technology</span><small>{{ $service->technologies->take(4)->pluck('name')->join(' · ') }}</small></div>@endif @if($service->benefits->isNotEmpty())<div><span>Business outcomes</span>@foreach($service->benefits->take(3) as $benefit)<small>{{ $benefit->title }}</small>@endforeach</div>@endif</div><a class="practice-arrow" href="{{ route('services.show',$service->slug) }}" aria-label="Explore {{ $service->name }}"><i class="bi bi-arrow-up-right"></i></a></article>@empty<x-empty-state title="No services found">Try changing the search or category filter.</x-empty-state>@endforelse</div><div class="mt-5">{{ $services->links() }}</div></div></section>
@php($technologyServices = $services->getCollection()->filter(fn($service) => $service->technologies->isNotEmpty()))
@if($technologyServices->isNotEmpty())<section class="technology-ledger"><div class="container"><div class="row g-5"><div class="col-lg-4"><p class="eyebrow">Technology stack</p><h2>Tools chosen for the work.</h2></div><div class="col-lg-8"><div class="technology-cloud">@foreach($technologyServices->flatMap->technologies->unique('name')->take(18) as $technology)<span>@if($technology->icon)<i class="bi bi-{{ $technology->icon }}"></i>@endif{{ $technology->name }}</span>@endforeach</div></div></div></div></section>@endif
@if($leadService)<section class="engagement-band"><div class="container"><div><p class="eyebrow">Engagement</p><h2>{{ $leadService->name }}</h2><p>{{ $leadService->short_description }}</p></div><div class="engagement-actions"><a class="btn btn-light" href="{{ route('quote-request',['type'=>'service','item'=>$leadService->id]) }}">Discuss the engagement</a><a href="{{ route('services.show',$leadService->slug) }}">Review methodology <i class="bi bi-arrow-right"></i></a></div></div></section>@endif
@endsection