@extends('layouts.app')
@section('title',$service->seo?->meta_title ?: $service->name) @section('description',$service->seo?->meta_description ?: $service->short_description) @section('canonical',$service->seo?->canonical_url ?: route('services.show',$service->slug))
@push('head')@if($service->seo && !$service->seo->is_indexable)<meta name="robots" content="noindex,nofollow">@endif<meta property="og:title" content="{{ $service->seo?->meta_title ?: $service->name }}"><meta property="og:description" content="{{ $service->seo?->meta_description ?: $service->short_description }}">@if($service->seo?->open_graph_image_path)<meta property="og:image" content="{{ url(Storage::url($service->seo->open_graph_image_path)) }}">@endif<script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'Service','name'=>$service->name,'description'=>$service->short_description,'provider'=>['@type'=>'Organization','name'=>'DevNiox'],'url'=>route('services.show',$service->slug)], JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) !!}</script>@endpush
@section('content')
<div class="container py-4"><nav aria-label="Breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li><li class="breadcrumb-item"><a href="{{ route('services') }}">Services</a></li><li class="breadcrumb-item active" aria-current="page">{{ $service->name }}</li></ol></nav></div><header class="container pb-5"><p class="text-primary fw-semibold">{{ $service->category->name }}</p><h1 class="display-4 fw-bold">{{ $service->name }}</h1><p class="lead col-lg-8">{{ $service->short_description }}</p>@if($service->featured_image_path || $service->cover_image_path)<img class="img-fluid rounded-4 mt-4 w-100 object-fit-cover" style="max-height:560px" src="{{ Storage::url($service->featured_image_path ?: $service->cover_image_path) }}" alt="{{ $service->name }} delivery overview">@endif</header>
<div class="container pb-5"><section class="mb-5"><p class="eyebrow">Business challenge</p><h2>What this engagement addresses</h2><div class="content-copy">{!! nl2br(e($service->full_description)) !!}</div></section>
@foreach([['Expected outcomes',$service->benefits],['Our approach',$service->features],['What your team receives',$service->deliverables]] as [$heading,$items])@if($items->isNotEmpty())<section class="mb-5"><h2>{{ $heading }}</h2><div class="row g-3">@foreach($items as $item)<div class="col-md-6"><article class="card h-100"><div class="card-body"><h3 class="h5">{{ $item->title }}</h3><p class="mb-0">{{ $item->description }}</p></div></article></div>@endforeach</div></section>@endif @endforeach
@if($service->processSteps->isNotEmpty())<section class="mb-5"><p class="eyebrow">Methodology</p><h2>How the engagement moves forward</h2><ol class="list-group list-group-numbered">@foreach($service->processSteps as $step)<li class="list-group-item"><strong>{{ $step->title }}</strong><p class="mb-0">{{ $step->description }}</p></li>@endforeach</ol></section>@endif
@if($service->technologies->isNotEmpty())<section class="mb-5"><p class="eyebrow">Technology</p><h2>Tools selected for the delivery context</h2><div class="d-flex flex-wrap gap-2">@foreach($service->technologies as $technology)<span class="badge text-bg-light border fs-6">{{ $technology->name }}</span>@endforeach</div></section>@endif
@if($service->galleryImages->isNotEmpty())<section class="mb-5"><h2>Gallery</h2><div class="row g-3">@foreach($service->galleryImages as $image)<div class="col-md-6"><img class="img-fluid rounded" src="{{ Storage::url($image->image_path) }}" alt="{{ $image->alt_text ?: $service->name }}" loading="lazy"></div>@endforeach</div></section>@endif
@if($service->faqs->isNotEmpty())<section class="mb-5"><h2>Frequently asked questions</h2><div class="accordion" id="service-faq">@foreach($service->faqs as $faq)<div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button @if(!$loop->first) collapsed @endif" type="button" data-bs-toggle="collapse" data-bs-target="#faq-{{ $faq->id }}" aria-expanded="{{ $loop->first?'true':'false' }}">{{ $faq->question }}</button></h3><div id="faq-{{ $faq->id }}" class="accordion-collapse collapse @if($loop->first) show @endif" data-bs-parent="#service-faq"><div class="accordion-body">{!! nl2br(e($faq->answer)) !!}</div></div></div>@endforeach</div></section>@endif
<section class="rounded-4 bg-dark text-white p-4 p-lg-5 mb-5"><p class="eyebrow text-white">Plan the engagement</p><h2>Define the outcome before estimating the work.</h2><p class="col-lg-8">Share the current workflow, affected teams, known constraints, required integrations, and the result the business needs to measure.</p><a class="btn btn-light" href="{{ route('quote-request',['type'=>'service','item'=>$service->id]) }}">Discuss {{ $service->name }}</a></section>@if($related->isNotEmpty())<section><h2>Related services</h2><div class="row g-4">@foreach($related as $item)<div class="col-md-4"><x-service-card :service="$item" /></div>@endforeach</div></section>@endif</div>
@endsection
