@extends('layouts.admin')
@section('title','About Editor')
@section('heading','About Page')
@section('content')
@php $c=$page->about; @endphp
<form method="post" enctype="multipart/form-data" action="{{ route('admin.cms.pages.update',$page) }}">
@csrf @method('PUT')
<x-card title="About content"><div class="row g-3">
@foreach(['hero_label','hero_heading','hero_description','hero_cta_text','story_label','story_title','story_description','mission_title','mission_description','vision_title','vision_description','philosophy_label','philosophy_title','process_label','process_title'] as $field)
<div class="col-md-6"><label class="form-label">{{ Str::headline($field) }}</label><textarea class="form-control" name="{{ $field }}" @if(in_array($field,['hero_heading','hero_description','story_title','story_description','mission_title','mission_description','vision_title','vision_description'])) required @endif>{{ old($field,$c->{$field}) }}</textarea></div>
@endforeach
@foreach(['hero_banner'=>'Hero banner','story_image'=>'Story image'] as $imageField=>$label)
@php($pathField=$imageField.'_path')
<div class="col-md-6"><label class="form-label">{{ $label }}</label>@if($c->{$pathField})<div class="mb-2"><img src="{{ Storage::url($c->{$pathField}) }}" alt="" style="max-width:220px;height:auto;border-radius:8px"></div><label class="form-check mb-2"><input class="form-check-input" type="checkbox" name="remove_images[{{ $imageField }}]" value="1"> Remove current {{ Str::lower($label) }}</label>@endif<input class="form-control" type="file" name="{{ $imageField }}" accept="image/png,image/jpeg,image/webp"></div>
@endforeach
</div></x-card>
<x-card title="Core values" class="mt-4"><div class="row g-3">@foreach(($page->coreValues->isNotEmpty() ? $page->coreValues : collect([(object)['title'=>'','description'=>'','icon'=>'','sort_order'=>0]])) as $index=>$item)<div class="col-12"><div class="row g-2"><div class="col-md-4"><label class="form-label">Title</label><input class="form-control" name="core_values[{{ $index }}][title]" value="{{ old('core_values.'.$index.'.title',$item->title) }}"></div><div class="col-md-2"><label class="form-label">Icon</label><input class="form-control" name="core_values[{{ $index }}][icon]" value="{{ old('core_values.'.$index.'.icon',$item->icon) }}"></div><div class="col-md-2"><label class="form-label">Order</label><input class="form-control" type="number" min="0" name="core_values[{{ $index }}][sort_order]" value="{{ old('core_values.'.$index.'.sort_order',$item->sort_order ?? $index) }}"></div><div class="col-md-4"><label class="form-label">Description</label><textarea class="form-control" name="core_values[{{ $index }}][description]">{{ old('core_values.'.$index.'.description',$item->description) }}</textarea></div></div></div>@endforeach</div></x-card>
<x-card title="Work items" class="mt-4"><div class="row g-3">@foreach(($page->workItems->isNotEmpty() ? $page->workItems : collect([(object)['title'=>'','description'=>'','icon'=>'','sort_order'=>0]])) as $index=>$item)<div class="col-12"><div class="row g-2"><div class="col-md-4"><label class="form-label">Title</label><input class="form-control" name="work_items[{{ $index }}][title]" value="{{ old('work_items.'.$index.'.title',$item->title) }}"></div><div class="col-md-2"><label class="form-label">Icon</label><input class="form-control" name="work_items[{{ $index }}][icon]" value="{{ old('work_items.'.$index.'.icon',$item->icon) }}"></div><div class="col-md-2"><label class="form-label">Order</label><input class="form-control" type="number" min="0" name="work_items[{{ $index }}][sort_order]" value="{{ old('work_items.'.$index.'.sort_order',$item->sort_order ?? $index) }}"></div><div class="col-md-4"><label class="form-label">Description</label><textarea class="form-control" name="work_items[{{ $index }}][description]">{{ old('work_items.'.$index.'.description',$item->description) }}</textarea></div></div></div>@endforeach</div></x-card>
@include('admin.cms.seo')<button class="btn btn-primary my-4">Publish about content</button></form>
@endsection
