@extends('layouts.app')
@section('title',$cmsPage->meta_title ?: 'Request a Demo')
@section('description',$cmsPage->meta_description ?: 'Request a guided DevNiox product or service demonstration.')
@section('canonical',$cmsPage->canonical_url ?: route('demo-request'))
@push('head')@unless($cmsPage->is_indexable)<meta name="robots" content="noindex,follow">@endunless @endpush
@section('content')
@php
    $c = $cmsPage->simpleContent;
    $steps = collect($c->steps ?: ['Select a system', 'Choose a time', 'Meet the product'])->filter()->values();
@endphp
<header class="demo-hero" @if($c->hero_banner_path)style="--hero-image:url('{{ Storage::url($c->hero_banner_path) }}')"@endif><div class="container"><div><p class="eyebrow">{{ $c->hero_label ?: 'Guided product session' }}</p><h1>{{ $c->hero_heading ?: 'See the system through your workflow.' }}</h1><p>{{ $c->hero_description ?: 'Choose the solution and a preferred time. The demonstration will focus on the operation you need to improve.' }}</p></div><ol>@foreach($steps as $step)<li><span>{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</span>{{ $step }}</li>@endforeach</ol></div></header>
<section class="lead-workspace demo-workspace"><div class="container"><div class="lead-workspace-grid"><aside><p class="eyebrow">{{ $c->intro_label ?: 'Request demo' }}</p><h2>{{ $c->intro_title ?: 'A focused conversation, not a sales presentation.' }}</h2><div class="workspace-note"><i class="bi bi-{{ $c->note_icon ?: 'camera-video' }}"></i><p>{{ $c->note_text ?: 'Your request is routed to the team responsible for the selected system.' }}</p></div></aside><div class="workspace-form"><x-lead-form-alerts/><form method="post" action="{{ route('demo-request.store') }}">@csrf<div class="form-chapter"><span>01</span><h3>{{ $c->chapter_one_label ?: 'Your details' }}</h3></div><x-lead-contact-fields :name-label="$c->name_label ?: 'Name'" :company-label="$c->company_label ?: 'Company'" :email-label="$c->email_label ?: 'Email'" :phone-label="$c->phone_label ?: 'Phone'"/><div class="form-chapter"><span>02</span><h3>{{ $c->chapter_two_label ?: 'Solution' }}</h3></div><x-lead-item-selector :products="$products" :services="$services" :selected-type="$selectedType" :selected-id="$selectedId" :item-type-label="$c->item_type_label ?: 'Item type'" :product-label="$c->item_id_label ?: 'Product'"/><div class="form-chapter"><span>03</span><h3>{{ $c->chapter_three_label ?: 'Schedule' }}</h3></div><div class="row g-3"><div class="col-md-6"><label class="form-label" for="preferred_date">{{ $c->preferred_date_label ?: 'Preferred date' }}</label><input class="form-control" id="preferred_date" type="date" name="preferred_date" min="{{ now()->toDateString() }}" value="{{ old('preferred_date') }}"></div><div class="col-md-6"><label class="form-label" for="preferred_time">{{ $c->preferred_time_label ?: 'Preferred time' }}</label><input class="form-control" id="preferred_time" type="time" name="preferred_time" value="{{ old('preferred_time') }}"></div><div class="col-12"><label class="form-label" for="message">{{ $c->message_label ?: 'What should we focus on?' }}</label><textarea class="form-control" id="message" name="message" rows="5" maxlength="10000">{{ old('message') }}</textarea></div></div><button class="btn btn-primary btn-lg mt-4">{{ $c->submit_button_text ?: 'Request demo' }} <i class="bi bi-arrow-right"></i></button></form></div></div></div></section>
@endsection
