@extends('layouts.app')
@section('title',$cmsPage->meta_title ?: 'Request a Quote')
@section('description',$cmsPage->meta_description ?: 'Request a DevNiox project or solution quote.')
@section('canonical',$cmsPage->canonical_url ?: route('quote-request'))
@push('head')@unless($cmsPage->is_indexable)<meta name="robots" content="noindex,follow">@endunless @endpush
@section('content')
@php
    $c = $cmsPage->simpleContent;
    $bullets = collect($c->bullets ?: ['Business objective', 'Preferred timeline', 'Investment context', 'Relevant documentation'])->filter()->values();
@endphp
<header class="quote-hero" @if($c->hero_banner_path)style="--hero-image:url('{{ Storage::url($c->hero_banner_path) }}')"@endif><div class="container"><p class="eyebrow">{{ $c->hero_label ?: 'Project planning' }}</p><div><h1>{{ $c->hero_heading ?: 'Turn the brief into an investment decision.' }}</h1><p>{{ $c->hero_description ?: 'Share the outcome, constraints, and context. We will use them to prepare a relevant commercial response.' }}</p></div></div></header>
<section class="lead-workspace quote-workspace"><div class="container"><div class="lead-workspace-grid"><aside><p class="eyebrow">{{ $c->intro_label ?: 'Request quote' }}</p><h2>{{ $c->intro_title ?: 'Enough context creates a better proposal.' }}</h2><ul>@foreach($bullets as $bullet)<li><i class="bi bi-check2"></i> {{ $bullet }}</li>@endforeach</ul></aside><div class="workspace-form"><x-lead-form-alerts/><form method="post" enctype="multipart/form-data" action="{{ route('quote-request.store') }}">@csrf<div class="form-chapter"><span>01</span><h3>{{ $c->chapter_one_label ?: 'Contact' }}</h3></div><x-lead-contact-fields :name-label="$c->name_label ?: 'Name'" :company-label="$c->company_label ?: 'Company'" :email-label="$c->email_label ?: 'Email'" :phone-label="$c->phone_label ?: 'Phone'"/><div class="form-chapter"><span>02</span><h3>{{ $c->chapter_two_label ?: 'Project context' }}</h3></div><x-lead-item-selector :products="$products" :services="$services" :portfolio-projects="$portfolioProjects" :allow-portfolio="true" :selected-type="$selectedType" :selected-id="$selectedId" :item-type-label="$c->item_type_label ?: 'Item type'"/><div class="form-chapter"><span>03</span><h3>{{ $c->chapter_three_label ?: 'Commercial context' }}</h3></div><div class="row g-3"><div class="col-md-6"><label class="form-label" for="budget">{{ $c->budget_label ?: 'Budget' }}</label><input class="form-control" id="budget" name="budget" maxlength="120" value="{{ old('budget') }}" placeholder="{{ $c->budget_placeholder ?: 'Example: USD 5,000-10,000' }}"></div><div class="col-md-6"><label class="form-label" for="timeline">{{ $c->timeline_label ?: 'Timeline' }}</label><input class="form-control" id="timeline" name="timeline" maxlength="120" value="{{ old('timeline') }}" placeholder="{{ $c->timeline_placeholder ?: 'Example: Within 3 months' }}"></div><div class="col-12"><label class="form-label" for="requirement_details">{{ $c->requirement_details_label ?: 'Requirement details' }}</label><textarea class="form-control" id="requirement_details" name="requirement_details" rows="7" required minlength="20" maxlength="30000">{{ old('requirement_details') }}</textarea></div><div class="col-12"><label class="form-label" for="attachment">{{ $c->attachment_label ?: 'Supporting document' }} <span class="text-muted">({{ $c->optional_label ?: 'optional, up to 10 MB' }})</span></label><input class="form-control" id="attachment" type="file" name="attachment" accept=".pdf,.doc,.docx,.xls,.xlsx,.png,.jpg,.jpeg,.webp"><div class="form-text">{{ $c->attachment_helper ?: 'PDF, Office documents, or common images.' }}</div></div></div><button class="btn btn-primary btn-lg mt-4">{{ $c->submit_button_text ?: 'Request quote' }} <i class="bi bi-arrow-right"></i></button></form></div></div></div></section>
@endsection
