@extends('layouts.admin')
@section('title', 'Dashboard')
@section('heading', 'Dashboard')
@section('content')
<div class="row g-3 mb-4">
@foreach([['Unread messages',$stats['unread_messages'],'envelope-exclamation','danger'],['Pending demos',$stats['pending_demo_requests'],'calendar-event','primary'],['Pending quotes',$stats['pending_quote_requests'],'file-earmark-text','warning'],["Today's communications",$stats['communications_today'],'chat-square-text','success']] as [$label,$value,$icon,$color])
<div class="col-sm-6 col-xl-3"><a class="text-decoration-none" href="{{ route('admin.leads.index') }}"><div class="small-box text-bg-{{ $color }}"><div class="inner"><h2>{{ $value }}</h2><p>{{ $label }}</p></div><i class="small-box-icon bi bi-{{ $icon }}" aria-hidden="true"></i></div></a></div>
@endforeach
</div><div class="row g-3 mb-4">
@foreach([['New leads today',$stats['new_leads_today'],'inbox','primary'],['Total leads',$stats['total_leads'],'people','info'],['Contact messages',$stats['contact_messages'],'envelope','secondary'],['Demo requests',$stats['demo_requests'],'play-btn','success'],['Quote requests',$stats['quote_requests'],'receipt','warning'],['Unread leads',$stats['unread_leads'],'exclamation-circle','danger'],['Users',$stats['users'],'people','primary'],['Active users',$stats['active_users'],'person-check','success'],['Products',$stats['products'],'box-seam','primary'],['Published products',$stats['published_products'],'check-circle','success'],['Featured products',$stats['featured_products'],'star','warning'],['Services',$stats['services'],'briefcase','primary'],['Published services',$stats['published_services'],'check-circle','success'],['Featured services',$stats['featured_services'],'star','warning'],['Configured settings',$stats['settings'],'sliders','info'],['Unread notifications',$stats['unread'],'bell','secondary']] as [$label,$value,$icon,$color])
<div class="col-sm-6 col-xl-3"><div class="small-box text-bg-{{ $color }}"><div class="inner"><h2>{{ $value }}</h2><p>{{ $label }}</p></div><i class="small-box-icon bi bi-{{ $icon }}" aria-hidden="true"></i></div></div>
@endforeach
</div>
<div class="row g-3 mb-4" aria-label="Media Library statistics">
<div class="col-sm-6 col-xl-3"><a class="text-decoration-none" href="{{ route('admin.media.index') }}"><div class="card shadow-sm h-100 border-start border-4 border-primary"><div class="card-body"><i class="bi bi-collection text-primary" aria-hidden="true"></i><p class="small text-body-secondary my-1">Media assets</p><strong>{{ number_format($stats['media_files']) }}</strong></div></div></a></div>
<div class="col-sm-6 col-xl-3"><a class="text-decoration-none" href="{{ route('admin.media.index') }}"><div class="card shadow-sm h-100 border-start border-4 border-success"><div class="card-body"><i class="bi bi-link-45deg text-success" aria-hidden="true"></i><p class="small text-body-secondary my-1">Assets in use</p><strong>{{ number_format($stats['media_used']) }}</strong></div></div></a></div>
<div class="col-sm-6 col-xl-3"><a class="text-decoration-none" href="{{ route('admin.media.index', ['kind' => 'image']) }}"><div class="card shadow-sm h-100 border-start border-4 border-info"><div class="card-body"><i class="bi bi-image text-info" aria-hidden="true"></i><p class="small text-body-secondary my-1">Images</p><strong>{{ number_format($stats['media_images']) }}</strong></div></div></a></div>
<div class="col-sm-6 col-xl-3"><a class="text-decoration-none" href="{{ route('admin.media.index') }}"><div class="card shadow-sm h-100 border-start border-4 border-secondary"><div class="card-body"><i class="bi bi-device-hdd text-secondary" aria-hidden="true"></i><p class="small text-body-secondary my-1">Media storage</p><strong>{{ number_format($stats['media_bytes'] / 1048576, 1) }} MB</strong></div></div></a></div>
</div>
<div class="row g-3 mb-4" aria-label="Finance statistics">@foreach([['Cash balance',$stats['cash_balance'],'wallet2','primary'],['Month income',$stats['month_income'],'arrow-down-circle','success'],['Month expense',$stats['month_expense'],'arrow-up-circle','danger'],['Pending receivables',$stats['pending_receivables'],'hourglass-split','info'],['Pending expenses',$stats['pending_expenses'],'clock','warning'],['Month net profit',$stats['month_net_profit'],'graph-up',$stats['month_net_profit']>=0?'success':'danger']] as [$label,$value,$icon,$color])<div class="col-sm-6 col-xl-2"><a class="text-decoration-none" href="{{ route('admin.finance.transactions.index') }}"><div class="card shadow-sm h-100 border-start border-4 border-{{ $color }}"><div class="card-body"><i class="bi bi-{{ $icon }} text-{{ $color }}" aria-hidden="true"></i><p class="small text-body-secondary my-1">{{ $label }}</p><strong>{{ number_format($value,2) }}</strong></div></div></a></div>@endforeach</div>
<div class="row g-3 mb-4" aria-label="Order statistics">@foreach([['Pending orders',$stats['pending_orders'],'hourglass-split','warning'],['Active orders',$stats['active_orders'],'kanban','primary'],['Completed orders',$stats['completed_orders'],'check-circle','success'],['Cancelled orders',$stats['cancelled_orders'],'x-circle','danger']] as [$label,$value,$icon,$color])<div class="col-sm-6 col-xl-3"><a class="text-decoration-none" href="{{ route('admin.orders.index') }}"><div class="small-box text-bg-{{ $color }}"><div class="inner"><h2>{{ $value }}</h2><p>{{ $label }}</p></div><i class="small-box-icon bi bi-{{ $icon }}" aria-hidden="true"></i></div></a></div>@endforeach</div>
<div class="row g-3 mb-4" aria-label="Portfolio statistics">@foreach([['Portfolio projects',$stats['portfolio_projects'],'images','primary'],['Published projects',$stats['published_portfolio_projects'],'check-circle','success'],['Draft projects',$stats['draft_portfolio_projects'],'pencil','secondary'],['Featured projects',$stats['featured_portfolio_projects'],'star','warning']] as [$label,$value,$icon,$color])<div class="col-sm-6 col-xl-3"><div class="small-box text-bg-{{ $color }}"><div class="inner"><h2>{{ $value }}</h2><p>{{ $label }}</p></div><i class="small-box-icon bi bi-{{ $icon }}" aria-hidden="true"></i></div></div>@endforeach</div>
<div class="row g-4">
<div class="col-12"><x-card title="Recent leads"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Lead</th><th>Type</th><th>Status</th><th>Submitted</th><th></th></tr></thead><tbody>@forelse($recentLeads as $lead)<tr><td><strong>{{ $lead->name }}</strong><br><small>{{ $lead->email }}</small></td><td>{{ Str::headline($lead->type->value) }}</td><td>{{ Str::headline($lead->status->value) }}</td><td>{{ $lead->submitted_at->diffForHumans() }}</td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.leads.show',$lead) }}">Open</a></td></tr>@empty<tr><td colspan="5"><x-empty-state title="No leads yet"/></td></tr>@endforelse</tbody></table></div></x-card></div>
<div class="col-lg-7"><x-card title="Recent activity"><div class="list-group list-group-flush">@forelse($recentUsers as $user)<div class="list-group-item d-flex flex-wrap justify-content-between gap-2"><span>{{ $user->name }} <small class="text-muted">{{ $user->role->value }}</small></span><time datetime="{{ $user->created_at->toAtomString() }}">{{ $user->created_at->diffForHumans() }}</time></div>@empty<x-empty-state>No user activity recorded.</x-empty-state>@endforelse</div></x-card></div>
<div class="col-lg-5"><x-card title="Latest notifications">@forelse($notifications as $note)<div class="notification-message mb-3"><strong>{{ $note->title }}</strong><br><span class="text-muted">{{ Str::limit($note->message,90) }}</span></div>@empty<x-empty-state>No notifications yet.</x-empty-state>@endforelse</x-card></div>
<div class="col-lg-7"><x-card title="Quick actions"><a class="btn btn-primary me-2 mb-2" href="{{ route('admin.products.create') }}"><i class="bi bi-plus-lg" aria-hidden="true"></i> Add product</a>@if(auth()->user()->isAdmin())<a class="btn btn-outline-primary me-2 mb-2" href="{{ route('admin.settings.edit') }}"><i class="bi bi-gear" aria-hidden="true"></i> Website settings</a>@endif<a class="btn btn-outline-secondary mb-2" href="{{ route('home') }}" target="_blank" rel="noopener">View site</a></x-card></div>
<div class="col-lg-5"><x-card title="System information"><dl class="row mb-0"><dt class="col-6">Laravel</dt><dd class="col-6">{{ app()->version() }}</dd><dt class="col-6">PHP</dt><dd class="col-6">{{ PHP_VERSION }}</dd><dt class="col-6">Environment</dt><dd class="col-6">{{ app()->environment() }}</dd></dl></x-card></div>
</div>
@endsection
