<div class="row g-3">
    <div class="col-md-6"><label class="form-label" for="name">Full name</label><input class="form-control" id="name" name="name" required maxlength="255" value="{{ old('name', $user->name ?? '') }}"></div>
    <div class="col-md-6"><label class="form-label" for="email">Email address</label><input class="form-control" id="email" type="email" name="email" required maxlength="255" value="{{ old('email', $user->email ?? '') }}"></div>
    <div class="col-md-6"><label class="form-label" for="phone">Phone <span class="text-muted fw-normal">(optional)</span></label><input class="form-control" id="phone" type="tel" name="phone" maxlength="40" value="{{ old('phone', $user->phone ?? '') }}" autocomplete="tel"></div>
    <div class="col-md-6"><label class="form-label" for="avatar">Avatar <span class="text-muted fw-normal">(optional)</span></label><input class="form-control" id="avatar" type="file" name="avatar" accept="image/jpeg,image/png,image/webp" aria-describedby="avatar-help"><div class="form-text" id="avatar-help">JPG, PNG or WebP, maximum 2 MB. A new upload safely replaces the current avatar.</div></div>
    @isset($user)@if($user->avatar_path)<div class="col-12"><img class="navbar-avatar" src="{{ asset('storage/'.$user->avatar_path) }}" alt="{{ $user->name }} avatar" width="64" height="64"></div>@endif @endisset
    <div class="col-md-6"><label class="form-label" for="role_id">Role</label><select class="form-select" id="role_id" name="role_id" required>@foreach($roles as $role)<option value="{{ $role->id }}" @selected((string) old('role_id', $user->role_id ?? '') === (string) $role->id)>{{ $role->name }}</option>@endforeach</select></div>
    <div class="col-md-6 d-flex align-items-end"><div class="form-check form-switch mb-2"><input type="hidden" name="is_active" value="0"><input class="form-check-input" id="is_active" type="checkbox" name="is_active" value="1" @checked((bool) old('is_active', $user->is_active ?? true))><label class="form-check-label" for="is_active">Active account</label></div></div>
    <div class="col-md-6"><label class="form-label" for="password">Password @isset($user)<span class="text-muted fw-normal">(leave blank to keep current)</span>@endisset</label><input class="form-control" id="password" type="password" name="password" @required(!isset($user)) autocomplete="new-password"></div>
    <div class="col-md-6"><label class="form-label" for="password_confirmation">Confirm password</label><input class="form-control" id="password_confirmation" type="password" name="password_confirmation" @required(!isset($user)) autocomplete="new-password"></div>
</div>
