@extends('layouts.admin')
@section('title', $order->exists ? 'Edit '.$order->order_number : 'Create Order')
@section('heading', $order->exists ? 'Edit '.$order->order_number : 'Create Order')
@section('content')
@php
$formItems = old('items', $order->exists ? $order->items->map(fn($item)=>['name'=>$item->name,'type'=>$item->type->value,'quantity'=>$item->quantity,'unit_price'=>$item->unit_price,'discount'=>$item->discount])->all() : [['name'=>'','type'=>'software','quantity'=>1,'unit_price'=>'0.00','discount'=>'0.00']]);
@endphp
<form method="POST" action="{{ $order->exists ? route('admin.orders.update',$order) : route('admin.orders.store') }}">@csrf @if($order->exists)@method('PUT')@endif
<div class="row g-4"><div class="col-12 col-xl-8">
<div class="card shadow-sm mb-4"><div class="card-header"><h2 class="h5 mb-0">Customer Information</h2></div><div class="card-body"><div class="row g-3">
<div class="col-md-6"><label class="form-label" for="customer_name">Customer Name *</label><input class="form-control" id="customer_name" name="customer_name" value="{{ old('customer_name',$order->customer_name) }}" required maxlength="160"></div><div class="col-md-6"><label class="form-label" for="company_name">Company Name</label><input class="form-control" id="company_name" name="company_name" value="{{ old('company_name',$order->company_name) }}" maxlength="180"></div><div class="col-md-6"><label class="form-label" for="email">Email *</label><input class="form-control" type="email" id="email" name="email" value="{{ old('email',$order->email) }}" required maxlength="254"></div><div class="col-md-6"><label class="form-label" for="phone">Phone</label><input class="form-control" id="phone" name="phone" value="{{ old('phone',$order->phone) }}" maxlength="40"></div><div class="col-md-6"><label class="form-label" for="whatsapp">WhatsApp</label><input class="form-control" id="whatsapp" name="whatsapp" value="{{ old('whatsapp',$order->whatsapp) }}" maxlength="40"></div><div class="col-12"><label class="form-label" for="address">Address</label><textarea class="form-control" id="address" name="address" rows="3" maxlength="3000">{{ old('address',$order->address) }}</textarea></div>
</div></div></div>
<div class="card shadow-sm"><div class="card-header d-flex justify-content-between align-items-center"><h2 class="h5 mb-0">Order Items</h2><button class="btn btn-sm btn-outline-primary" id="add-order-item" type="button"><i class="bi bi-plus-lg" aria-hidden="true"></i> Add Item</button></div><div class="card-body"><div id="order-items" class="vstack gap-3">@foreach($formItems as $index=>$item)<div class="order-item border rounded p-3"><div class="row g-3"><div class="col-12 col-lg-5"><label class="form-label">Product / Service Name *</label><input class="form-control" name="items[{{ $index }}][name]" value="{{ $item['name'] }}" required maxlength="200"></div><div class="col-6 col-lg-3"><label class="form-label">Type *</label><select class="form-select" name="items[{{ $index }}][type]" required>@foreach($itemTypes as $type)<option value="{{ $type->value }}" @selected($item['type']===$type->value)>{{ str($type->value)->headline() }}</option>@endforeach</select></div><div class="col-6 col-lg-2"><label class="form-label">Quantity *</label><input class="form-control" type="number" name="items[{{ $index }}][quantity]" value="{{ $item['quantity'] }}" min="1" max="1000000" required></div><div class="col-6 col-lg-2"><label class="form-label">Unit Price *</label><input class="form-control" type="number" name="items[{{ $index }}][unit_price]" value="{{ $item['unit_price'] }}" min="0" step="0.01" required></div><div class="col-6 col-lg-2"><label class="form-label">Discount *</label><input class="form-control" type="number" name="items[{{ $index }}][discount]" value="{{ $item['discount'] }}" min="0" step="0.01" required></div><div class="col-12 col-lg-auto ms-auto d-flex align-items-end"><button class="btn btn-outline-danger remove-order-item" type="button" aria-label="Remove item"><i class="bi bi-trash" aria-hidden="true"></i> Remove</button></div></div></div>@endforeach</div></div></div>
</div><div class="col-12 col-xl-4">
<div class="card shadow-sm mb-4"><div class="card-header"><h2 class="h5 mb-0">Order Information</h2></div><div class="card-body"><div class="vstack gap-3"><div><label class="form-label" for="order_date">Order Date *</label><input class="form-control" type="date" id="order_date" name="order_date" value="{{ old('order_date',$order->order_date?->format('Y-m-d')) }}" required></div><div><label class="form-label" for="expected_delivery_date">Expected Delivery</label><input class="form-control" type="date" id="expected_delivery_date" name="expected_delivery_date" value="{{ old('expected_delivery_date',$order->expected_delivery_date?->format('Y-m-d')) }}"></div><div><label class="form-label" for="priority">Priority *</label><select class="form-select" id="priority" name="priority" required>@foreach($priorities as $priority)<option value="{{ $priority->value }}" @selected(old('priority',$order->priority?->value)===$priority->value)>{{ str($priority->value)->headline() }}</option>@endforeach</select></div><div><label class="form-label" for="status">Status *</label><select class="form-select" id="status" name="status" required>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(old('status',$order->status?->value)===$status->value)>{{ str($status->value)->headline() }}</option>@endforeach</select></div><div><label class="form-label" for="source">Source *</label><select class="form-select" id="source" name="source" required>@foreach($sources as $source)<option value="{{ $source->value }}" @selected(old('source',$order->source?->value)===$source->value)>{{ str($source->value)->headline() }}</option>@endforeach</select></div><div><label class="form-label" for="lead_id">Source Lead</label><select class="form-select" id="lead_id" name="lead_id"><option value="">Select a lead</option>@foreach($leads as $lead)<option value="{{ $lead->id }}" @selected((string)old('lead_id',$order->lead_id)===(string)$lead->id)>#{{ $lead->id }} — {{ $lead->name }} ({{ $lead->email }})</option>@endforeach</select></div></div></div></div>
<div class="card shadow-sm mb-4"><div class="card-header"><h2 class="h5 mb-0">Payment Tracking</h2></div><div class="card-body"><div class="vstack gap-3"><div><label class="form-label" for="discount">Order Discount *</label><input class="form-control" type="number" id="discount" name="discount" value="{{ old('discount',$order->discount ?? '0.00') }}" min="0" step="0.01" required></div><div><label class="form-label" for="paid_amount">Paid Amount *</label><input class="form-control" type="number" id="paid_amount" name="paid_amount" value="{{ old('paid_amount',$order->paid_amount ?? '0.00') }}" min="0" step="0.01" required></div><div><label class="form-label" for="payment_method">Payment Method</label><select class="form-select" id="payment_method" name="payment_method"><option value="">Not selected</option>@foreach($paymentMethods as $method)<option value="{{ $method->value }}" @selected(old('payment_method',$order->payment_method?->value)===$method->value)>{{ str($method->value)->headline() }}</option>@endforeach</select><div class="form-text">Required when a paid amount is recorded.</div></div><div class="border rounded p-3"><div class="form-check"><input class="form-check-input" type="checkbox" id="sync_finance" name="sync_finance" value="1" @checked(old('sync_finance'))><label class="form-check-label fw-semibold" for="sync_finance">Create linked Finance transaction</label></div><div class="form-text mb-2">Once linked, later payment changes synchronize automatically without duplicates.</div><label class="form-label" for="finance_income_category_id">Income Category</label><select class="form-select" id="finance_income_category_id" name="finance_income_category_id"><option value="">Select income category</option>@foreach($financeIncomeCategories as $category)<option value="{{ $category->id }}" @selected((string)old('finance_income_category_id')===(string)$category->id)>{{ $category->name }}</option>@endforeach</select></div></div></div></div>
<div class="d-grid gap-2"><button class="btn btn-primary btn-lg" type="submit">{{ $order->exists?'Update Order':'Create Order' }}</button>@if($order->exists)<a class="btn btn-outline-secondary" href="{{ route('admin.orders.show',$order) }}">Cancel</a>@endif</div>
</div></div></form>
<template id="order-item-template"><div class="order-item border rounded p-3"><div class="row g-3"><div class="col-12 col-lg-5"><label class="form-label">Product / Service Name *</label><input class="form-control" name="items[__INDEX__][name]" required maxlength="200"></div><div class="col-6 col-lg-3"><label class="form-label">Type *</label><select class="form-select" name="items[__INDEX__][type]" required>@foreach($itemTypes as $type)<option value="{{ $type->value }}">{{ str($type->value)->headline() }}</option>@endforeach</select></div><div class="col-6 col-lg-2"><label class="form-label">Quantity *</label><input class="form-control" type="number" name="items[__INDEX__][quantity]" value="1" min="1" required></div><div class="col-6 col-lg-2"><label class="form-label">Unit Price *</label><input class="form-control" type="number" name="items[__INDEX__][unit_price]" value="0.00" min="0" step="0.01" required></div><div class="col-6 col-lg-2"><label class="form-label">Discount *</label><input class="form-control" type="number" name="items[__INDEX__][discount]" value="0.00" min="0" step="0.01" required></div><div class="col-12 col-lg-auto ms-auto d-flex align-items-end"><button class="btn btn-outline-danger remove-order-item" type="button"><i class="bi bi-trash" aria-hidden="true"></i> Remove</button></div></div></div></template>
<script>document.addEventListener('DOMContentLoaded',()=>{const list=document.getElementById('order-items'),template=document.getElementById('order-item-template');let index=list.children.length;document.getElementById('add-order-item').addEventListener('click',()=>{list.insertAdjacentHTML('beforeend',template.innerHTML.replaceAll('__INDEX__',index++));});list.addEventListener('click',event=>{const button=event.target.closest('.remove-order-item');if(button&&list.children.length>1)button.closest('.order-item').remove();});});</script>
@endsection
