@extends('layouts.admin')
@section('title', 'Orders')
@section('heading', 'Orders')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><p class="text-body-secondary mb-0">Manage agency projects, deliveries and payment tracking.</p><a class="btn btn-primary" href="{{ route('admin.orders.create') }}"><i class="bi bi-plus-lg me-1" aria-hidden="true"></i>Create Order</a></div>
<div class="card shadow-sm mb-3"><div class="card-body"><form class="row g-2 align-items-end" method="GET" aria-label="Order filters">
<div class="col-12 col-xl-3"><label class="form-label" for="order-search">Search</label><input class="form-control" id="order-search" name="search" value="{{ request('search') }}" placeholder="Order, customer, company, email"></div>
<div class="col-6 col-md-3 col-xl"><label class="form-label" for="order-status">Status</label><select class="form-select" id="order-status" name="status"><option value="">All</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ str($status->value)->headline() }}</option>@endforeach</select></div>
<div class="col-6 col-md-3 col-xl"><label class="form-label" for="order-priority">Priority</label><select class="form-select" id="order-priority" name="priority"><option value="">All</option>@foreach($priorities as $priority)<option value="{{ $priority->value }}" @selected(request('priority')===$priority->value)>{{ str($priority->value)->headline() }}</option>@endforeach</select></div>
<div class="col-6 col-md-3 col-xl"><label class="form-label" for="payment-status">Payment</label><select class="form-select" id="payment-status" name="payment_status"><option value="">All</option>@foreach($paymentStatuses as $status)<option value="{{ $status->value }}" @selected(request('payment_status')===$status->value)>{{ str($status->value)->headline() }}</option>@endforeach</select></div>
<div class="col-6 col-md-3 col-xl"><label class="form-label" for="order-from">From</label><input class="form-control" id="order-from" type="date" name="date_from" value="{{ request('date_from') }}"></div><div class="col-6 col-md-3 col-xl"><label class="form-label" for="order-to">To</label><input class="form-control" id="order-to" type="date" name="date_to" value="{{ request('date_to') }}"></div>
<div class="col-auto"><div class="form-check mb-2"><input class="form-check-input" id="archived" type="checkbox" name="archived" value="1" @checked(request('archived')==='1')><label class="form-check-label" for="archived">Archived</label></div></div><div class="col-auto"><button class="btn btn-outline-primary" type="submit">Filter</button></div><div class="col-auto"><a class="btn btn-outline-secondary" href="{{ route('admin.orders.index') }}">Reset</a></div>
</form></div></div>
<form method="POST" action="{{ route('admin.orders.bulk') }}">@csrf
<div class="d-flex flex-wrap gap-2 mb-3"><select class="form-select w-auto" name="action" required aria-label="Bulk action"><option value="">Bulk action</option><option value="status">Change status</option>@if(auth()->user()->isAdmin())<option value="archive">Archive</option><option value="delete">Delete</option>@endif</select><select class="form-select w-auto" name="status" aria-label="Bulk order status"><option value="">Choose status</option>@foreach($statuses as $status)<option value="{{ $status->value }}">{{ str($status->value)->headline() }}</option>@endforeach</select><button class="btn btn-secondary" type="submit">Apply</button></div>
<div class="card shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><caption class="visually-hidden">Agency orders</caption><thead><tr><th><input type="checkbox" data-select-all aria-label="Select all orders"></th><th>Order</th><th>Customer</th><th>Items</th><th>Status</th><th>Priority</th><th>Payment</th><th>Final</th><th>Due</th><th>Delivery</th><th class="text-end">Actions</th></tr></thead><tbody>
@forelse($orders as $order)<tr><td><input type="checkbox" name="order_ids[]" value="{{ $order->id }}" aria-label="Select {{ $order->order_number }}"></td><td><a class="fw-semibold text-decoration-none" href="{{ route('admin.orders.show',$order) }}">{{ $order->order_number }}</a><br><small class="text-body-secondary">{{ $order->order_date->format('M j, Y') }}</small></td><td><strong>{{ $order->customer_name }}</strong><br><small>{{ $order->company_name ?: $order->email }}</small></td><td>{{ $order->items_count }}</td><td><span class="badge text-bg-{{ $order->status===\App\Enums\OrderStatus::Completed?'success':($order->status===\App\Enums\OrderStatus::Cancelled?'danger':'primary') }}">{{ str($order->status->value)->headline() }}</span></td><td>{{ str($order->priority->value)->headline() }}</td><td><span class="badge text-bg-{{ $order->payment_status===\App\Enums\PaymentStatus::Paid?'success':($order->payment_status===\App\Enums\PaymentStatus::Partial?'warning':'secondary') }}">{{ str($order->payment_status->value)->headline() }}</span></td><td>{{ number_format((float)$order->final_amount,2) }}</td><td>{{ number_format((float)$order->due_amount,2) }}</td><td>{{ $order->expected_delivery_date?->format('M j, Y') ?? 'Flexible' }}</td><td class="text-end text-nowrap"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.orders.show',$order) }}">Open</a><a class="btn btn-sm btn-outline-secondary" href="{{ route('admin.orders.edit',$order) }}">Edit</a></td></tr>
@empty<tr><td colspan="11"><x-empty-state title="No orders found"><a class="btn btn-primary mt-2" href="{{ route('admin.orders.create') }}">Create the first order</a></x-empty-state></td></tr>@endforelse
</tbody></table></div>@if($orders->hasPages())<div class="card-footer">{{ $orders->links() }}</div>@endif</div></form>
@endsection
