@extends('layouts.admin')
@section('title', $product->exists ? 'Edit Product' : 'New Product')
@section('heading', $product->exists ? 'Edit Product' : 'New Product')
@section('content')
@php
    $highlights = old('highlights', $product->exists ? $product->highlights->toArray() : []);
    $modules = old('modules', $product->exists ? $product->modules->toArray() : []);
    $features = old('features', $product->exists ? $product->features->toArray() : []);
    $plans = old('pricing_plans', $product->exists ? $product->pricingPlans->map(fn ($plan) => array_merge($plan->toArray(), ['feature_list' => $plan->features->pluck('feature')->implode("\n")]))->toArray() : []);
    $faqs = old('faqs', $product->exists ? $product->faqs->toArray() : []);
@endphp
<form method="post" enctype="multipart/form-data" action="{{ $product->exists ? route('admin.products.update', $product) : route('admin.products.store') }}">@csrf @if($product->exists) @method('PUT') @endif
<div class="row g-4"><div class="col-xl-9">
<x-card title="Basic information">
<div class="row"><div class="col-md-8"><x-form.input name="name" label="Product name" :value="$product->name" required data-slug-source /></div><div class="col-md-4"><x-form.input name="version" label="Version" :value="$product->version" required placeholder="1.0.0" /></div></div>
<div class="row"><div class="col-md-8"><x-form.input name="slug" label="Slug" :value="$product->slug" required data-slug-target /></div><div class="col-md-4"><x-form.input name="display_order" label="Display order" type="number" :value="$product->display_order ?? 0" min="0" required /></div></div>
<div class="mb-3"><label class="form-label" for="short_description">Short description</label><textarea class="form-control @error('short_description') is-invalid @enderror" id="short_description" name="short_description" maxlength="300" rows="3" required>{{ old('short_description', $product->short_description) }}</textarea>@error('short_description')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="mb-3"><label class="form-label" for="full_description">Full description</label><textarea class="form-control @error('full_description') is-invalid @enderror" id="full_description" name="full_description" rows="12" required>{{ old('full_description', $product->full_description) }}</textarea>@error('full_description')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
</x-card>

<x-card title="Branding" class="mt-4"><div class="row g-3">@foreach(['thumbnail'=>'Thumbnail','banner'=>'Banner','logo'=>'Logo'] as $field=>$label)<div class="col-md-4"><label class="form-label" for="{{ $field }}">{{ $label }}</label>@if($product->{$field.'_path'})<img class="image-preview mb-2" src="{{ Storage::url($product->{$field.'_path'}) }}" alt="Current {{ strtolower($label) }}">@endif<input class="form-control @error($field) is-invalid @enderror" id="{{ $field }}" name="{{ $field }}" type="file" accept=".png,.jpg,.jpeg,.webp" data-image-input>@error($field)<div class="invalid-feedback">{{ $message }}</div>@enderror</div>@endforeach</div></x-card>

<x-card title="Product highlights" class="mt-4"><div data-repeater><div data-repeater-items>
@foreach($highlights as $index=>$item)<div class="repeater-item"><div class="row g-2"><div class="col-md-4"><input class="form-control" name="highlights[{{ $index }}][title]" value="{{ $item['title']??'' }}" placeholder="Title" required></div><div class="col-md-3"><input class="form-control" name="highlights[{{ $index }}][icon]" value="{{ $item['icon']??'' }}" placeholder="Icon"></div><div class="col-md-2"><input class="form-control" type="number" min="0" name="highlights[{{ $index }}][sort_order]" value="{{ $item['sort_order']??$index }}" aria-label="Sort order" required></div><div class="col-md-3 text-end"><button class="btn btn-outline-danger" type="button" data-repeater-remove>Remove</button></div><div class="col-12"><textarea class="form-control" name="highlights[{{ $index }}][description]" placeholder="Description" required>{{ $item['description']??'' }}</textarea></div></div></div>@endforeach
</div><template><div class="repeater-item"><div class="row g-2"><div class="col-md-4"><input class="form-control" name="highlights[__INDEX__][title]" placeholder="Title" required></div><div class="col-md-3"><input class="form-control" name="highlights[__INDEX__][icon]" placeholder="Icon"></div><div class="col-md-2"><input class="form-control" type="number" min="0" name="highlights[__INDEX__][sort_order]" value="__INDEX__" aria-label="Sort order" required></div><div class="col-md-3 text-end"><button class="btn btn-outline-danger" type="button" data-repeater-remove>Remove</button></div><div class="col-12"><textarea class="form-control" name="highlights[__INDEX__][description]" placeholder="Description" required></textarea></div></div></div></template><button class="btn btn-outline-primary mt-3" type="button" data-repeater-add>Add highlight</button></div></x-card>

<x-card title="Core modules" class="mt-4"><div data-repeater><div data-repeater-items>@foreach($modules as $index=>$item)<div class="repeater-item"><div class="row g-2"><div class="col-md-5"><input class="form-control" name="modules[{{ $index }}][name]" value="{{ $item['name']??'' }}" placeholder="Module name" required></div><div class="col-md-2"><input class="form-control" type="number" min="0" name="modules[{{ $index }}][sort_order]" value="{{ $item['sort_order']??$index }}" aria-label="Sort order" required></div><div class="col-md-5 text-end"><button class="btn btn-outline-danger" type="button" data-repeater-remove>Remove</button></div><div class="col-12"><textarea class="form-control" name="modules[{{ $index }}][description]" placeholder="Description">{{ $item['description']??'' }}</textarea></div></div></div>@endforeach</div><template><div class="repeater-item"><div class="row g-2"><div class="col-md-5"><input class="form-control" name="modules[__INDEX__][name]" placeholder="Module name" required></div><div class="col-md-2"><input class="form-control" type="number" min="0" name="modules[__INDEX__][sort_order]" value="__INDEX__" aria-label="Sort order" required></div><div class="col-md-5 text-end"><button class="btn btn-outline-danger" type="button" data-repeater-remove>Remove</button></div><div class="col-12"><textarea class="form-control" name="modules[__INDEX__][description]" placeholder="Description"></textarea></div></div></div></template><button class="btn btn-outline-primary mt-3" type="button" data-repeater-add>Add module</button></div></x-card>

<x-card title="Features" class="mt-4"><div data-repeater><div data-repeater-items>@foreach($features as $index=>$item)<div class="repeater-item"><div class="row g-2"><div class="col-md-4"><input class="form-control" name="features[{{ $index }}][title]" value="{{ $item['title']??'' }}" placeholder="Title" required></div><div class="col-md-3"><input class="form-control" name="features[{{ $index }}][icon]" value="{{ $item['icon']??'' }}" placeholder="Icon"></div><div class="col-md-2"><input class="form-control" type="number" min="0" name="features[{{ $index }}][sort_order]" value="{{ $item['sort_order']??$index }}" aria-label="Sort order" required></div><div class="col-md-3 text-end"><button class="btn btn-outline-danger" type="button" data-repeater-remove>Remove</button></div><div class="col-12"><textarea class="form-control" name="features[{{ $index }}][description]" placeholder="Description" required>{{ $item['description']??'' }}</textarea></div></div></div>@endforeach</div><template><div class="repeater-item"><div class="row g-2"><div class="col-md-4"><input class="form-control" name="features[__INDEX__][title]" placeholder="Title" required></div><div class="col-md-3"><input class="form-control" name="features[__INDEX__][icon]" placeholder="Icon"></div><div class="col-md-2"><input class="form-control" type="number" min="0" name="features[__INDEX__][sort_order]" value="__INDEX__" aria-label="Sort order" required></div><div class="col-md-3 text-end"><button class="btn btn-outline-danger" type="button" data-repeater-remove>Remove</button></div><div class="col-12"><textarea class="form-control" name="features[__INDEX__][description]" placeholder="Description" required></textarea></div></div></div></template><button class="btn btn-outline-primary mt-3" type="button" data-repeater-add>Add feature</button></div></x-card>

<x-card title="System requirements" class="mt-4"><div class="row"><div class="col-md-4"><x-form.input name="requirements[php_version]" label="PHP version" :value="$product->requirements?->php_version" /></div><div class="col-md-4"><x-form.input name="requirements[laravel_version]" label="Laravel version" :value="$product->requirements?->laravel_version" /></div><div class="col-md-4"><x-form.input name="requirements[database]" label="Database" :value="$product->requirements?->database" /></div><div class="col-md-6"><x-form.input name="requirements[hosting]" label="Hosting" :value="$product->requirements?->hosting" /></div><div class="col-md-6"><x-form.input name="requirements[browser_support]" label="Browser support" :value="$product->requirements?->browser_support" /></div></div><div class="mb-3"><label class="form-label" for="server_requirements">Server requirements</label><textarea class="form-control" id="server_requirements" name="requirements[server_requirements]" rows="4">{{ old('requirements.server_requirements',$product->requirements?->server_requirements) }}</textarea></div></x-card>

<x-card title="Gallery" class="mt-4">@if($product->exists)<div class="row g-3 mb-3">@foreach($product->galleryImages as $image)<div class="col-md-6"><div class="gallery-admin-item"><img src="{{ Storage::url($image->image_path) }}" alt="{{ $image->alt_text }}"><div class="row g-2 mt-1"><div class="col-8"><input class="form-control" name="gallery_existing[{{ $image->id }}][alt_text]" value="{{ old('gallery_existing.'.$image->id.'.alt_text',$image->alt_text) }}" placeholder="Alt text"></div><div class="col-4"><input class="form-control" type="number" min="0" name="gallery_existing[{{ $image->id }}][sort_order]" value="{{ old('gallery_existing.'.$image->id.'.sort_order',$image->sort_order) }}" aria-label="Sort order"></div><div class="col-8"><input class="form-control" type="file" name="gallery_replacements[{{ $image->id }}]" accept=".png,.jpg,.jpeg,.webp" aria-label="Replace image"></div><div class="col-4"><label class="form-check"><input class="form-check-input" type="checkbox" name="gallery_remove[]" value="{{ $image->id }}"> Remove</label></div></div></div></div>@endforeach</div>@endif<label class="form-label" for="gallery_images">Add screenshots</label><input class="form-control" id="gallery_images" name="gallery_images[]" type="file" accept=".png,.jpg,.jpeg,.webp" multiple></x-card>

<x-card title="Demo and resources" class="mt-4"><x-form.input name="links[live_demo_url]" label="Live demo URL" type="url" :value="$product->links?->live_demo_url" /><x-form.input name="links[video_url]" label="Video URL" type="url" :value="$product->links?->video_url" /><x-form.input name="links[documentation_url]" label="Documentation URL" type="url" :value="$product->links?->documentation_url" /></x-card>

<x-card title="Pricing plans" class="mt-4"><div data-repeater><div data-repeater-items>@foreach($plans as $index=>$plan)<div class="repeater-item"><div class="row g-2"><div class="col-md-4"><input class="form-control" name="pricing_plans[{{ $index }}][name]" value="{{ $plan['name']??'' }}" placeholder="Plan name" required></div><div class="col-md-3"><input class="form-control" type="number" step="0.01" min="0" name="pricing_plans[{{ $index }}][price]" value="{{ $plan['price']??'' }}" placeholder="Price"></div><div class="col-md-2"><input class="form-control text-uppercase" name="pricing_plans[{{ $index }}][currency]" value="{{ $plan['currency']??'USD' }}" maxlength="3" required></div><div class="col-md-3"><select class="form-select" name="pricing_plans[{{ $index }}][billing_type]" required>@foreach(\App\Enums\BillingType::cases() as $billing)<option value="{{ $billing->value }}" @selected(($plan['billing_type']??'')===$billing->value)>{{ Str::headline($billing->value) }}</option>@endforeach</select></div><div class="col-12"><textarea class="form-control" name="pricing_plans[{{ $index }}][description]" placeholder="Description">{{ $plan['description']??'' }}</textarea></div><div class="col-md-8"><textarea class="form-control" name="pricing_plans[{{ $index }}][feature_list]" rows="5" placeholder="One included feature per line">{{ $plan['feature_list']??'' }}</textarea></div><div class="col-md-4"><input type="hidden" name="pricing_plans[{{ $index }}][is_highlighted]" value="0"><label class="form-check"><input class="form-check-input" type="checkbox" name="pricing_plans[{{ $index }}][is_highlighted]" value="1" @checked($plan['is_highlighted']??false)> Highlight plan</label><input type="hidden" name="pricing_plans[{{ $index }}][is_active]" value="0"><label class="form-check"><input class="form-check-input" type="checkbox" name="pricing_plans[{{ $index }}][is_active]" value="1" @checked($plan['is_active']??true)> Active</label><label class="form-label mt-2">Sort order<input class="form-control" type="number" min="0" name="pricing_plans[{{ $index }}][sort_order]" value="{{ $plan['sort_order']??$index }}" required></label><button class="btn btn-outline-danger d-block" type="button" data-repeater-remove>Remove</button></div></div></div>@endforeach</div>
<template><div class="repeater-item"><div class="row g-2"><div class="col-md-4"><input class="form-control" name="pricing_plans[__INDEX__][name]" placeholder="Plan name" required></div><div class="col-md-3"><input class="form-control" type="number" step="0.01" min="0" name="pricing_plans[__INDEX__][price]" placeholder="Price"></div><div class="col-md-2"><input class="form-control text-uppercase" name="pricing_plans[__INDEX__][currency]" value="USD" maxlength="3" required></div><div class="col-md-3"><select class="form-select" name="pricing_plans[__INDEX__][billing_type]" required>@foreach(\App\Enums\BillingType::cases() as $billing)<option value="{{ $billing->value }}">{{ Str::headline($billing->value) }}</option>@endforeach</select></div><div class="col-12"><textarea class="form-control" name="pricing_plans[__INDEX__][description]" placeholder="Description"></textarea></div><div class="col-md-8"><textarea class="form-control" name="pricing_plans[__INDEX__][feature_list]" rows="5" placeholder="One included feature per line"></textarea></div><div class="col-md-4"><input type="hidden" name="pricing_plans[__INDEX__][is_highlighted]" value="0"><label class="form-check"><input class="form-check-input" type="checkbox" name="pricing_plans[__INDEX__][is_highlighted]" value="1"> Highlight plan</label><input type="hidden" name="pricing_plans[__INDEX__][is_active]" value="0"><label class="form-check"><input class="form-check-input" type="checkbox" name="pricing_plans[__INDEX__][is_active]" value="1" checked> Active</label><label class="form-label mt-2">Sort order<input class="form-control" type="number" min="0" name="pricing_plans[__INDEX__][sort_order]" value="__INDEX__" required></label><button class="btn btn-outline-danger d-block" type="button" data-repeater-remove>Remove</button></div></div></div></template><button class="btn btn-outline-primary mt-3" type="button" data-repeater-add>Add pricing plan</button></div></x-card>

<x-card title="Frequently asked questions" class="mt-4"><div data-repeater><div data-repeater-items>@foreach($faqs as $index=>$faq)<div class="repeater-item"><div class="row g-2"><div class="col-md-8"><input class="form-control" name="faqs[{{ $index }}][question]" value="{{ $faq['question']??'' }}" placeholder="Question" required></div><div class="col-md-2"><input class="form-control" type="number" min="0" name="faqs[{{ $index }}][sort_order]" value="{{ $faq['sort_order']??$index }}" aria-label="Sort order" required></div><div class="col-md-2"><button class="btn btn-outline-danger" type="button" data-repeater-remove>Remove</button></div><div class="col-12"><textarea class="form-control" name="faqs[{{ $index }}][answer]" placeholder="Answer" required>{{ $faq['answer']??'' }}</textarea></div></div></div>@endforeach</div><template><div class="repeater-item"><div class="row g-2"><div class="col-md-8"><input class="form-control" name="faqs[__INDEX__][question]" placeholder="Question" required></div><div class="col-md-2"><input class="form-control" type="number" min="0" name="faqs[__INDEX__][sort_order]" value="__INDEX__" aria-label="Sort order" required></div><div class="col-md-2"><button class="btn btn-outline-danger" type="button" data-repeater-remove>Remove</button></div><div class="col-12"><textarea class="form-control" name="faqs[__INDEX__][answer]" placeholder="Answer" required></textarea></div></div></div></template><button class="btn btn-outline-primary mt-3" type="button" data-repeater-add>Add FAQ</button></div></x-card>

<x-card title="SEO" class="mt-4"><x-form.input name="seo[meta_title]" label="Meta title" :value="$product->seo?->meta_title" maxlength="70" /><div class="mb-3"><label class="form-label" for="meta_description">Meta description</label><textarea class="form-control" id="meta_description" name="seo[meta_description]" maxlength="160" rows="3">{{ old('seo.meta_description',$product->seo?->meta_description) }}</textarea></div><x-form.input name="seo[keywords]" label="Keywords" :value="$product->seo?->keywords" maxlength="500" /><x-form.input name="seo[canonical_url]" label="Canonical URL" type="url" :value="$product->seo?->canonical_url" />@if($product->seo?->open_graph_image_path)<img class="image-preview mb-2" src="{{ Storage::url($product->seo->open_graph_image_path) }}" alt="Current Open Graph image">@endif<div class="mb-3"><label class="form-label" for="open_graph_image">Open Graph image</label><input class="form-control" id="open_graph_image" name="seo[open_graph_image]" type="file" accept=".png,.jpg,.jpeg,.webp"></div><input type="hidden" name="seo[is_indexable]" value="0"><label class="form-check"><input class="form-check-input" type="checkbox" name="seo[is_indexable]" value="1" @checked(old('seo.is_indexable',$product->seo?->is_indexable??true))> Allow search engine indexing</label></x-card>
</div>
<div class="col-xl-3"><div class="sticky-xl-top product-publish-panel"><x-card title="Publishing"><div class="mb-3"><label class="form-label" for="product_category_id">Category</label><select class="form-select" id="product_category_id" name="product_category_id" required><option value="">Select category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)old('product_category_id',$product->product_category_id)===(string)$category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label" for="status">Status</label><select class="form-select" id="status" name="status" required>@foreach($statuses as $status)@if($status !== \App\Enums\ProductStatus::Archived || auth()->user()->isAdmin())<option value="{{ $status->value }}" @selected(old('status',$product->status?->value??'draft')===$status->value)>{{ Str::headline($status->value) }}</option>@endif @endforeach</select></div><input type="hidden" name="is_featured" value="0">@if(auth()->user()->isAdmin())<label class="form-check mb-3"><input class="form-check-input" type="checkbox" name="is_featured" value="1" @checked(old('is_featured',$product->is_featured))> Featured product</label>@endif<button class="btn btn-primary w-100" type="submit">Save product</button><a class="btn btn-outline-secondary w-100 mt-2" href="{{ route('admin.products.index') }}">Cancel</a></x-card></div></div>
</div></form>
@endsection
