@extends('layouts.admin')
@section('title', 'Products')
@section('heading', 'Products')
@section('content')
<div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><div>@if(auth()->user()->isAdmin())<a class="btn btn-outline-secondary" href="{{ route('admin.product-categories.index') }}">Categories</a>@endif</div><a class="btn btn-primary" href="{{ route('admin.products.create') }}"><i class="bi bi-plus-lg" aria-hidden="true"></i> Add product</a></div>
<x-card>
<form class="row g-2 mb-4" method="get"><div class="col-lg-4"><label class="visually-hidden" for="search">Search products</label><input class="form-control" id="search" name="search" value="{{ request('search') }}" placeholder="Search products"></div><div class="col-sm-4 col-lg-2"><select class="form-select" name="status" aria-label="Status"><option value="">All statuses</option>@foreach(['draft','published','archived'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ Str::headline($status) }}</option>@endforeach</select></div><div class="col-sm-4 col-lg-3"><select class="form-select" name="category" aria-label="Category"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)request('category')===(string)$category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="col-sm-4 col-lg-2"><select class="form-select" name="featured" aria-label="Featured"><option value="">Any featured</option><option value="1" @selected(request('featured')==='1')>Featured</option><option value="0" @selected(request('featured')==='0')>Not featured</option></select></div><div class="col-lg-1"><button class="btn btn-outline-primary w-100" type="submit">Filter</button></div></form>
<form method="post" action="{{ route('admin.products.bulk') }}" data-confirm="Apply this action to the selected products?">@csrf
<div class="d-flex flex-wrap gap-2 mb-3"><select class="form-select bulk-action-select" name="action" required><option value="">Bulk action</option><option value="publish">Publish</option><option value="draft">Draft</option>@if(auth()->user()->isAdmin())<option value="archive">Archive</option><option value="delete">Delete</option><option value="feature">Feature</option><option value="unfeature">Unfeature</option>@endif</select><button class="btn btn-outline-primary" type="submit">Apply</button></div>
<div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th><input class="form-check-input" type="checkbox" data-select-all aria-label="Select all products"></th><th>Image</th><th><a href="{{ request()->fullUrlWithQuery(['sort'=>'name','direction'=>request('direction')==='asc'?'desc':'asc']) }}">Product Name</a></th><th>Category</th><th>Version</th><th>Status</th><th>Featured</th><th>Updated</th><th class="text-end">Actions</th></tr></thead><tbody>
@forelse($products as $product)<tr><td><input class="form-check-input" type="checkbox" name="product_ids[]" value="{{ $product->id }}" aria-label="Select {{ $product->name }}"></td><td>@if($product->thumbnail_path)<img class="admin-product-thumb" src="{{ Storage::url($product->thumbnail_path) }}" alt="">@else<div class="admin-product-thumb placeholder-glow"><i class="bi bi-image" aria-hidden="true"></i></div>@endif</td><td><strong>{{ $product->name }}</strong><br><small class="text-muted">{{ $product->slug }}</small></td><td>{{ $product->category->name }}</td><td>{{ $product->version }}</td><td><span class="badge text-bg-{{ $product->status->value==='published'?'success':($product->status->value==='archived'?'secondary':'warning') }}">{{ Str::headline($product->status->value) }}</span></td><td><i class="bi bi-{{ $product->is_featured?'star-fill text-warning':'star' }}" aria-label="{{ $product->is_featured?'Featured':'Not featured' }}"></i></td><td><time datetime="{{ $product->updated_at->toAtomString() }}">{{ $product->updated_at->diffForHumans() }}</time></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.products.edit', $product) }}">Edit</a>@can('delete',$product)<form class="d-inline" method="post" action="{{ route('admin.products.destroy',$product) }}" data-confirm="Delete this product?">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" type="submit">Delete</button></form>@endcan</td></tr>
@empty<tr><td colspan="9"><x-empty-state title="No products found">Adjust the filters or create the first product.</x-empty-state></td></tr>@endforelse
</tbody></table></div></form>{{ $products->links() }}
</x-card>
@endsection
