@extends('layouts.app')
@section('title','Blog & Knowledge Center')
@section('description','Technical articles, software guides, business insights, and DevNiox news.')
@section('canonical',route('blog'))
@section('content')
@php($featuredPost = $posts->first())
<header class="editorial-hero"><div class="container"><div class="editorial-masthead"><div><p class="eyebrow">DevNiox knowledge center</p><h1>Signals for people building digital systems.</h1></div><a href="{{ route('blog.rss') }}"><i class="bi bi-rss"></i> Follow via RSS</a></div>@if($featuredPost)<article class="featured-story"><a class="featured-story-media" href="{{ route('blog.show',$featuredPost->slug) }}">@if($featuredPost->featured_image_path)<img src="{{ Storage::url($featuredPost->featured_image_path) }}" alt="{{ $featuredPost->title }}" width="1200" height="720">@else<div class="editorial-placeholder"><span>{{ $featuredPost->category->name }}</span></div>@endif</a><div class="featured-story-copy"><p>{{ $featuredPost->category->name }} · {{ $featuredPost->reading_time }} min read</p><h2><a href="{{ route('blog.show',$featuredPost->slug) }}">{{ $featuredPost->title }}</a></h2><div>{{ $featuredPost->summary }}</div><div class="editorial-byline"><span>{{ Str::substr($featuredPost->author->name,0,1) }}</span><p><strong>{{ $featuredPost->author->name }}</strong><time datetime="{{ $featuredPost->published_at->toDateString() }}">{{ $featuredPost->published_at->format('F j, Y') }}</time></p></div></div></article>@endif</div></header>
<section class="editorial-tools"><div class="container"><form method="get" role="search"><i class="bi bi-search"></i><label class="visually-hidden" for="blog-search">Search articles</label><input id="blog-search" name="search" value="{{ request('search') }}" placeholder="Search the knowledge center"><label class="visually-hidden" for="blog-category">Category</label><select id="blog-category" name="category"><option value="">All topics</option>@foreach($categories as $category)<option value="{{ $category->slug }}" @selected(request('category')===$category->slug)>{{ $category->name }} ({{ $category->posts_count }})</option>@endforeach</select><button class="btn btn-dark">Search</button></form>@if($categories->isNotEmpty())<nav aria-label="Article categories">@foreach($categories as $category)<a href="{{ route('blog',['category'=>$category->slug]) }}">{{ $category->name }}</a>@endforeach</nav>@endif</div></section>
<section class="knowledge-grid"><div class="container"><div class="row g-5"><div class="col-lg-8"><div class="editorial-section-title"><p class="eyebrow">Latest thinking</p><h2>From the editorial desk</h2></div><div class="story-list">@forelse($posts as $post)<article class="story-row"><a class="story-thumb" href="{{ route('blog.show',$post->slug) }}">@if($post->featured_image_path)<img loading="lazy" src="{{ Storage::url($post->featured_image_path) }}" alt="{{ $post->title }}" width="480" height="320">@else<div class="editorial-placeholder"><span>{{ $post->category->name }}</span></div>@endif</a><div><p class="story-meta">{{ $post->category->name }} · {{ $post->reading_time }} min read</p><h3><a href="{{ route('blog.show',$post->slug) }}">{{ $post->title }}</a></h3><p>{{ $post->summary }}</p><small>{{ $post->author->name }} · {{ $post->published_at->format('M j, Y') }}</small></div></article>@empty<x-empty-state title="No articles found"/>@endforelse</div><div class="mt-5">{{ $posts->links() }}</div></div><aside class="col-lg-4">@if($popularPosts->isNotEmpty())<div class="popular-panel"><p class="eyebrow">Most read</p><h2>Popular with readers</h2><ol>@foreach($popularPosts as $post)<li><span>{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</span><div><a href="{{ route('blog.show',$post->slug) }}">{{ $post->title }}</a><small>{{ $post->reading_time }} min · {{ number_format($post->views_count) }} views</small></div></li>@endforeach</ol></div>@endif @if($tags->isNotEmpty())<div class="topic-index"><h2>Explore topics</h2>@foreach($tags->sortByDesc('posts_count')->take(16) as $tag)<a href="{{ route('blog',['tag'=>$tag->slug]) }}">{{ $tag->name }} <span>{{ $tag->posts_count }}</span></a>@endforeach</div>@endif</aside></div></div></section>
@endsection