@extends('layouts.app')
@section('title', 'Products — DevNiox')
@section('description', 'Explore production-ready software products engineered by DevNiox.')
@section('canonical', route('products'))
@section('content')
@php($leadProduct = $featuredProducts->first() ?? $products->first())
<header class="catalog-hero product-catalog-hero"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-5"><p class="eyebrow">Software catalogue</p>@if($leadProduct)<p class="catalog-category">{{ $leadProduct->category->name }} · v{{ $leadProduct->version }}</p><h1>{{ $leadProduct->name }}</h1><p class="catalog-lead">{{ $leadProduct->short_description }}</p><div class="hero-actions"><a class="btn btn-primary btn-lg" href="{{ route('products.show',$leadProduct->slug) }}">Explore product <i class="bi bi-arrow-right"></i></a><a class="btn btn-outline-secondary btn-lg" href="{{ route('demo-request',['type'=>'product','item'=>$leadProduct->id]) }}">Request demo</a></div>@else<h1>Software built for real operations.</h1><p class="catalog-lead">{{ $siteSettings['seo.meta_description'] ?? '' }}</p>@endif</div><div class="col-lg-7">@if($leadProduct)<a class="product-stage" href="{{ route('products.show',$leadProduct->slug) }}" aria-label="Explore {{ $leadProduct->name }}">@if($leadProduct->banner_path || $leadProduct->thumbnail_path)<img src="{{ Storage::url($leadProduct->banner_path ?: $leadProduct->thumbnail_path) }}" alt="{{ $leadProduct->name }} dashboard preview" width="1000" height="625">@else<x-software-preview :product="$leadProduct" />@endif<div class="stage-chips">@foreach($leadProduct->modules->take(3) as $module)<span>{{ $module->name }}</span>@endforeach</div></a>@endif</div></div></div></header>
@if($categories->isNotEmpty())<nav class="catalog-categories" aria-label="Product categories"><div class="container"><a class="{{ $selectedCategory ? '' : 'active' }}" href="{{ route('products') }}">All products</a>@foreach($categories as $category)<a class="{{ $selectedCategory === $category->slug ? 'active' : '' }}" href="{{ route('products',['category'=>$category->slug]) }}">@if($category->icon)<i class="bi bi-{{ $category->icon }}"></i>@endif{{ $category->name }}</a>@endforeach</div></nav>@endif
<section class="catalog-search"><div class="container"><form method="get" role="search"><label class="visually-hidden" for="product-search">Search products</label><input id="product-search" class="form-control" name="search" value="{{ $search ?? request('search') }}" placeholder="Search products">@if($selectedCategory)<input type="hidden" name="category" value="{{ $selectedCategory }}">@endif<button class="btn btn-primary">Search</button>@if(($search ?? null) || $selectedCategory)<a class="btn btn-outline-secondary" href="{{ route('products') }}">Clear</a>@endif</form></div></section><section class="product-library"><div class="container"><div class="catalog-heading"><div><p class="eyebrow">Product suite</p><h2>{{ $selectedCategory ? $categories->firstWhere('slug',$selectedCategory)?->name : 'Software for growing operations' }}</h2></div><p>{{ $products->total() }} {{ Str::plural('product',$products->total()) }}</p></div><div class="product-library-grid">@forelse($products as $product)@php($startingPlan = $product->pricingPlans->whereNotNull('price')->sortBy('price')->first())<article class="software-catalog-card"><a class="software-preview" href="{{ route('products.show',$product->slug) }}">@if($product->thumbnail_path)<img loading="lazy" src="{{ Storage::url($product->thumbnail_path) }}" alt="{{ $product->name }} interface preview" width="900" height="560">@else<x-software-preview :product="$product" compact />@endif</a><div class="software-card-copy"><div class="card-meta"><span>{{ $product->category->name }}</span><span>v{{ $product->version }}</span></div><h3><a href="{{ route('products.show',$product->slug) }}">{{ $product->name }}</a></h3><p>{{ $product->short_description }}</p>@if($product->highlights->isNotEmpty())<ul class="product-highlights" aria-label="Key features">@foreach($product->highlights->take(3) as $highlight)<li><i class="bi bi-check2"></i>{{ $highlight->title }}</li>@endforeach</ul>@endif<div class="software-card-footer"><span>@if($startingPlan) Starting at <strong>{{ $startingPlan->currency }} {{ number_format((float) $startingPlan->price) }}</strong> @else Commercial pricing on request @endif</span><a href="{{ route('products.show',$product->slug) }}">View details <i class="bi bi-arrow-up-right"></i></a></div></div></article>@empty<x-empty-state title="No products found">There are no published products in this category yet.</x-empty-state>@endforelse</div><div class="mt-5">{{ $products->links() }}</div></div></section>
@if($leadProduct)<section class="product-cta-band"><div class="container"><div><p class="eyebrow">Product consultation</p><h2>{{ $leadProduct->name }}</h2><p>{{ $leadProduct->short_description }}</p></div><a class="btn btn-light btn-lg" href="{{ route('demo-request',['type'=>'product','item'=>$leadProduct->id]) }}">Request a guided demo</a></div></section>@endif
@endsection
