@extends('layouts.app')
@section('title', ($product->seo?->meta_title ?: $product->name).' — DevNiox')
@section('description', $product->seo?->meta_description ?: $product->short_description)
@section('canonical', $product->seo?->canonical_url ?: route('products.show', $product->slug))
@push('head')
@if(!$product->seo?->is_indexable)<meta name="robots" content="noindex, nofollow">@endif
@if($product->seo?->open_graph_image_path)<meta property="og:image" content="{{ url(Storage::url($product->seo->open_graph_image_path)) }}">@endif
<script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'SoftwareApplication','name'=>$product->name,'description'=>$product->short_description,'applicationCategory'=>$product->category->name,'softwareVersion'=>$product->version,'url'=>route('products.show',$product->slug)], JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) !!}</script>
@endpush
@section('content')
<div class="container pt-4"><nav aria-label="Breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li><li class="breadcrumb-item"><a href="{{ route('products') }}">Products</a></li><li class="breadcrumb-item"><a href="{{ route('products',['category'=>$product->category->slug]) }}">{{ $product->category->name }}</a></li><li class="breadcrumb-item active" aria-current="page">{{ $product->name }}</li></ol></nav></div>
<section class="product-hero"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-6"><p class="eyebrow">{{ $product->category->name }} · v{{ $product->version }}</p><h1>{{ $product->name }}</h1><p class="lead text-muted my-4">{{ $product->short_description }}</p><div class="d-flex flex-wrap gap-2">@if($product->links?->live_demo_url)<a class="btn btn-primary btn-lg" href="{{ $product->links->live_demo_url }}" target="_blank" rel="noopener noreferrer">Live demo</a>@endif @if($product->links?->documentation_url)<a class="btn btn-outline-secondary btn-lg" href="{{ $product->links->documentation_url }}" target="_blank" rel="noopener noreferrer">Documentation</a>@endif</div></div><div class="col-lg-6">@if($product->banner_path)<img class="product-banner" src="{{ Storage::url($product->banner_path) }}" alt="{{ $product->name }} interface">@elseif($product->thumbnail_path)<img class="product-banner" src="{{ Storage::url($product->thumbnail_path) }}" alt="{{ $product->name }}">@endif</div></div></div></section>
<section class="page-section"><div class="container"><p class="eyebrow">Product overview</p><h2 class="mb-4">Where {{ $product->name }} fits</h2><div class="product-description col-lg-9">{!! nl2br(e($product->full_description)) !!}</div></div></section>
@if($product->highlights->isNotEmpty())<section class="pb-5"><div class="container"><p class="eyebrow">Business problems solved</p><h2 class="mb-4">Why teams choose {{ $product->name }}</h2><div class="row g-4">@foreach($product->highlights as $highlight)<div class="col-md-6 col-xl-4"><div class="feature-card">@if($highlight->icon)<i class="bi bi-{{ $highlight->icon }} fs-2" aria-hidden="true"></i>@endif<h3 class="h5 mt-3">{{ $highlight->title }}</h3><p class="text-muted mb-0">{{ $highlight->description }}</p></div></div>@endforeach</div></div></section>@endif
@if($product->modules->isNotEmpty())<section class="page-section bg-body"><div class="container"><p class="eyebrow">Core modules</p><h2 class="mb-4">Everything your operation needs</h2><div class="row g-3">@foreach($product->modules as $module)<div class="col-md-6"><div class="feature-card"><h3 class="h5">{{ $module->name }}</h3><p class="text-muted mb-0">{{ $module->description }}</p></div></div>@endforeach</div></div></section>@endif
@if($product->features->isNotEmpty())<section class="page-section"><div class="container"><p class="eyebrow">Operational benefits</p><h2 class="mb-4">Capabilities for daily work</h2><div class="row g-4">@foreach($product->features as $feature)<div class="col-md-6 col-xl-4"><div class="d-flex gap-3">@if($feature->icon)<i class="bi bi-{{ $feature->icon }} fs-4" aria-hidden="true"></i>@endif<div><h3 class="h5">{{ $feature->title }}</h3><p class="text-muted">{{ $feature->description }}</p></div></div></div>@endforeach</div></div></section>@endif
<section class="page-section product-fit-section"><div class="container"><div class="row g-4"><div class="col-md-4"><p class="eyebrow">Typical users</p><h2 class="h4">Teams responsible for {{ Str::lower($product->category->name) }} workflows</h2><p>Use a guided demo to map roles, permissions, approvals, and reporting needs to the product.</p></div><div class="col-md-4"><p class="eyebrow">Business fit</p><h2 class="h4">Operations replacing fragmented tools</h2><p>{{ $product->short_description }}</p></div><div class="col-md-4"><p class="eyebrow">Evaluation</p><h2 class="h4">Version {{ $product->version }}</h2><p>Review deployment requirements, integrations, commercial options, and ownership before deciding.</p></div></div></div></section>@if($product->galleryImages->isNotEmpty())<section class="pb-5"><div class="container"><p class="eyebrow">Product screenshots</p><h2 class="mb-4">Review the working interface</h2><div class="row g-4">@foreach($product->galleryImages as $image)<div class="col-md-6"><img class="gallery-image" src="{{ Storage::url($image->image_path) }}" alt="{{ $image->alt_text ?: $product->name.' screenshot' }}" loading="lazy"></div>@endforeach</div></div></section>@endif
@if($product->pricingPlans->isNotEmpty())<section class="page-section bg-body"><div class="container"><p class="eyebrow">Pricing</p><h2 class="mb-4">Choose the right plan</h2><div class="row g-4 justify-content-center">@foreach($product->pricingPlans as $plan)<div class="col-md-6 col-xl-4"><article class="pricing-card {{ $plan->is_highlighted?'pricing-card-highlighted':'' }}"><h3>{{ $plan->name }}</h3><p class="pricing-value">{{ $plan->billing_type->value==='custom'?'Contact us':$plan->currency.' '.number_format((float)$plan->price,2) }}</p><p class="text-muted">{{ Str::headline($plan->billing_type->value) }}</p><p>{{ $plan->description }}</p><ul>@foreach($plan->features as $feature)<li>{{ $feature->feature }}</li>@endforeach</ul></article></div>@endforeach</div></div></section>@endif
@if($product->requirements)<section class="page-section"><div class="container"><p class="eyebrow">Requirements</p><h2 class="mb-4">System requirements</h2><dl class="row requirements-list">@foreach(['php_version'=>'PHP','laravel_version'=>'Laravel','database'=>'Database','hosting'=>'Hosting','browser_support'=>'Browser support','server_requirements'=>'Server'] as $field=>$label)@if($product->requirements->{$field})<dt class="col-sm-4">{{ $label }}</dt><dd class="col-sm-8">{{ $product->requirements->{$field} }}</dd>@endif @endforeach</dl></div></section>@endif
@if($product->faqs->isNotEmpty())<section class="pb-5"><div class="container col-lg-9"><p class="eyebrow">FAQ</p><h2 class="mb-4">Common questions</h2><div class="accordion" id="product-faq">@foreach($product->faqs as $faq)<div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-{{ $faq->id }}" aria-expanded="false" aria-controls="faq-{{ $faq->id }}">{{ $faq->question }}</button></h3><div id="faq-{{ $faq->id }}" class="accordion-collapse collapse" data-bs-parent="#product-faq"><div class="accordion-body">{!! nl2br(e($faq->answer)) !!}</div></div></div>@endforeach</div></div></section>@endif
<section class="page-section"><div class="container"><div class="closing-cta"><div><p class="eyebrow">Evaluate {{ $product->name }}</p><h2>See how it handles your actual workflow.</h2><p>Bring your user roles, current process, integration questions, and reporting requirements to a guided product review.</p></div><div class="cta-actions"><a class="btn btn-light btn-lg" href="{{ route('demo-request',['type'=>'product','item'=>$product->id]) }}">Request a guided demo</a><a class="btn btn-outline-light btn-lg" href="{{ route('quote-request',['type'=>'product','item'=>$product->id]) }}">Request commercial details</a></div></div></div></section>@if($relatedProducts->isNotEmpty())<section class="page-section"><div class="container"><p class="eyebrow">Related</p><h2 class="mb-4">More {{ $product->category->name }} products</h2><div class="row g-4">@foreach($relatedProducts as $related)<div class="col-md-6 col-xl-3"><x-product-card :product="$related" /></div>@endforeach</div></div></section>@endif
@endsection
