@extends('layouts.admin')
@section('title', 'Activity Log')
@section('heading', 'Activity Log')
@section('content')
<div class="card shadow-sm mb-4"><div class="card-body"><form method="GET" action="{{ route('admin.activity-logs.index') }}" class="row g-3 align-items-end" aria-label="Filter activity log">
<div class="col-12 col-xl-4"><label class="form-label" for="activity-search">Search</label><input class="form-control" id="activity-search" name="search" value="{{ request('search') }}" placeholder="Description, module or action"></div>
<div class="col-12 col-md-4 col-xl-2"><label class="form-label" for="activity-user">User</label><select class="form-select" id="activity-user" name="user"><option value="">All users</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string) request('user') === (string) $user->id)>{{ $user->name }}</option>@endforeach</select></div>
<div class="col-6 col-md-4 col-xl-2"><label class="form-label" for="activity-module">Module</label><select class="form-select" id="activity-module" name="module"><option value="">All modules</option>@foreach($modules as $module)<option value="{{ $module }}" @selected(request('module') === $module)>{{ str($module)->headline() }}</option>@endforeach</select></div>
<div class="col-6 col-md-4 col-xl-2"><label class="form-label" for="activity-action">Action</label><select class="form-select" id="activity-action" name="action"><option value="">All actions</option>@foreach($actions as $action)<option value="{{ $action }}" @selected(request('action') === $action)>{{ str($action)->headline() }}</option>@endforeach</select></div>
<div class="col-6 col-md-3 col-xl-2"><label class="form-label" for="activity-from">From</label><input class="form-control" type="date" id="activity-from" name="date_from" value="{{ request('date_from') }}"></div>
<div class="col-6 col-md-3 col-xl-2"><label class="form-label" for="activity-to">To</label><input class="form-control" type="date" id="activity-to" name="date_to" value="{{ request('date_to') }}"></div>
<div class="col-12 col-md-auto d-flex gap-2"><button class="btn btn-primary" type="submit"><i class="bi bi-funnel me-1" aria-hidden="true"></i>Filter</button><a class="btn btn-outline-secondary" href="{{ route('admin.activity-logs.index') }}">Reset</a></div></form></div></div>
<div class="card shadow-sm"><div class="card-header d-flex justify-content-between align-items-center"><h2 class="h5 mb-0">Administrative activity</h2><span class="text-body-secondary small">{{ number_format($logs->total()) }} records</span></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><caption class="visually-hidden">Recorded administrator activity</caption><thead><tr><th scope="col">Time</th><th scope="col">User</th><th scope="col">Module</th><th scope="col">Action</th><th scope="col">Description</th><th scope="col" class="text-end">Details</th></tr></thead><tbody>
@forelse($logs as $log)<tr><td class="text-nowrap"><time datetime="{{ $log->created_at->toIso8601String() }}">{{ $log->created_at->format('M j, Y H:i') }}</time></td><td><div class="fw-semibold">{{ $log->user?->name ?? 'Unauthenticated' }}</div><small class="text-body-secondary">{{ $log->user?->email ?? $log->ip_address }}</small></td><td><span class="badge text-bg-light border">{{ str($log->module)->headline() }}</span></td><td><span class="badge text-bg-primary-subtle text-primary-emphasis">{{ str($log->action)->headline() }}</span></td><td>{{ $log->description }}</td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.activity-logs.show', $log) }}" aria-label="View details for activity {{ $log->id }}">View</a></td></tr>@empty<tr><td colspan="6" class="text-center py-5"><i class="bi bi-clock-history fs-2 text-body-secondary" aria-hidden="true"></i><p class="mt-2 mb-0 fw-semibold">No activity matches these filters.</p><p class="text-body-secondary small mb-0">New administrative actions will appear here automatically.</p></td></tr>@endforelse
</tbody></table></div>@if($logs->hasPages())<div class="card-footer">{{ $logs->links() }}</div>@endif</div>
@endsection
