@extends('layouts.admin')
@section('title', 'Activity Details')
@section('heading', 'Activity Details')
@section('content')
<div class="mb-3"><a class="btn btn-outline-secondary" href="{{ route('admin.activity-logs.index') }}"><i class="bi bi-arrow-left me-1" aria-hidden="true"></i>Back to activity log</a></div>
<div class="row g-4"><div class="col-12 col-xl-8"><div class="card shadow-sm h-100"><div class="card-header"><h2 class="h5 mb-0">{{ $log->description }}</h2></div><div class="card-body"><dl class="row mb-0"><dt class="col-sm-4">User</dt><dd class="col-sm-8">{{ $log->user?->name ?? 'Unauthenticated' }} @if($log->user)<span class="text-body-secondary">({{ $log->user->email }})</span>@endif</dd><dt class="col-sm-4">Module</dt><dd class="col-sm-8">{{ str($log->module)->headline() }}</dd><dt class="col-sm-4">Action</dt><dd class="col-sm-8">{{ str($log->action)->headline() }}</dd><dt class="col-sm-4">Subject</dt><dd class="col-sm-8">{{ $log->subject_type ? class_basename($log->subject_type).' #'.$log->subject_id : '—' }}</dd><dt class="col-sm-4">Recorded</dt><dd class="col-sm-8"><time datetime="{{ $log->created_at->toIso8601String() }}">{{ $log->created_at->format('F j, Y \a\t H:i:s') }}</time></dd><dt class="col-sm-4">IP address</dt><dd class="col-sm-8"><code>{{ $log->ip_address ?? 'Unavailable' }}</code></dd></dl></div></div></div>
<div class="col-12 col-xl-4"><div class="card shadow-sm h-100"><div class="card-header"><h2 class="h5 mb-0">Request context</h2></div><div class="card-body"><p class="small text-body-secondary mb-2">User agent</p><p class="text-break mb-0">{{ $log->user_agent ?? 'Unavailable' }}</p></div></div></div>
@foreach(['old_values' => 'Previous values', 'new_values' => 'New values'] as $field => $label)<div class="col-12 col-lg-6"><div class="card shadow-sm h-100"><div class="card-header"><h2 class="h5 mb-0">{{ $label }}</h2></div><div class="card-body">@if($log->{$field})<pre class="activity-json bg-body-tertiary border rounded p-3 mb-0"><code>{{ json_encode($log->{$field}, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}</code></pre>@else<p class="text-body-secondary mb-0">No values were captured for this action.</p>@endif</div></div></div>@endforeach</div>
@endsection
