@extends('layouts.admin')
@section('title','Platforms')
@section('heading','Platforms')
@section('content')
<x-card title="Parent Company Settings" class="mb-4"><form method="post" enctype="multipart/form-data" action="{{ route('admin.platforms.parent.update') }}">@csrf @method('PUT')<div class="row g-3"><div class="col-md-6"><label class="form-label">Parent Company Name</label><input class="form-control" name="parent_company_name" required maxlength="255" value="{{ old('parent_company_name',$parent['company.parent_company_name'] ?? 'Ravoltify Technologies') }}"></div><div class="col-md-6"><label class="form-label">Parent Company Badge</label><input class="form-control" name="parent_company_badge" maxlength="100" value="{{ old('parent_company_badge',$parent['company.parent_company_badge'] ?? 'Parent Company') }}"></div><div class="col-12"><label class="form-label">Parent Company Description</label><textarea class="form-control" name="parent_company_description" rows="3">{{ old('parent_company_description',$parent['company.parent_company_description'] ?? '') }}</textarea></div><div class="col-md-6"><label class="form-label">Parent Company Logo</label>@if(filled($parent['company.parent_company_logo'] ?? null))<img class="image-preview d-block mb-2" src="{{ Storage::url($parent['company.parent_company_logo']) }}" alt="Current parent company logo">@endif<input class="form-control" type="file" name="parent_company_logo" accept=".png,.jpg,.jpeg,.webp,.svg">@error('parent_company_logo')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div></div><hr class="my-4"><h3 class="h6">Parent Company Highlights</h3><div class="row g-3">@foreach([1,2,3] as $number)<div class="col-lg-4"><label class="form-label">Highlight {{ $number }} Title</label><input class="form-control" name="parent_highlight_{{ $number }}_title" maxlength="255" value="{{ old('parent_highlight_'.$number.'_title',$parent['company.parent_highlight_'.$number.'_title'] ?? '') }}"><label class="form-label mt-2">Description</label><textarea class="form-control" name="parent_highlight_{{ $number }}_description" rows="3">{{ old('parent_highlight_'.$number.'_description',$parent['company.parent_highlight_'.$number.'_description'] ?? '') }}</textarea></div>@endforeach</div><button class="btn btn-primary mt-4">Save Parent Company Settings</button></form></x-card>
<div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">Sister Concerns / Platforms</h2><a class="btn btn-primary" href="{{ route('admin.platforms.create') }}"><i class="bi bi-plus-lg" aria-hidden="true"></i> Add platform</a></div>
<x-card>
<form class="row g-2 mb-4" method="get"><div class="col-lg-6"><label class="visually-hidden" for="search">Search platforms</label><input class="form-control" id="search" name="search" value="{{ request('search') }}" placeholder="Search platforms"></div><div class="col-sm-4 col-lg-3"><select class="form-select" name="status" aria-label="Status"><option value="">All statuses</option>@foreach(['active','inactive'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ Str::headline($status) }}</option>@endforeach</select></div><div class="col-sm-4 col-lg-2"><button class="btn btn-outline-primary w-100" type="submit">Filter</button></div></form>
<div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Logo</th><th>Platform</th><th>URL</th><th>Badge</th><th>Order</th><th>Status</th><th>Updated</th><th class="text-end">Actions</th></tr></thead><tbody>
@forelse($platforms as $platform)<tr><td>@if($platform->logo)<img class="admin-product-thumb" src="{{ Storage::url($platform->logo) }}" alt="">@else<div class="admin-product-thumb"><i class="bi bi-grid-3x3-gap" aria-hidden="true"></i></div>@endif</td><td><strong>{{ $platform->name }}</strong><br><small class="text-muted">{{ $platform->slug }}</small></td><td><a href="{{ $platform->website_url }}" target="_blank" rel="noopener noreferrer">{{ Str::limit($platform->website_url, 42) }}</a></td><td>{{ $platform->badge ?: '—' }}</td><td>{{ $platform->display_order }}</td><td><span class="badge text-bg-{{ $platform->status === 'active' ? 'success' : 'secondary' }}">{{ Str::headline($platform->status) }}</span></td><td><time datetime="{{ $platform->updated_at->toAtomString() }}">{{ $platform->updated_at->diffForHumans() }}</time></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.platforms.edit',$platform) }}">Edit</a><form class="d-inline" method="post" action="{{ route('admin.platforms.destroy',$platform) }}" data-confirm="Delete this platform?">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete</button></form></td></tr>
@empty<tr><td colspan="8"><x-empty-state title="No platforms found">Create the first platform to show the ecosystem section on the homepage.</x-empty-state></td></tr>@endforelse
</tbody></table></div>{{ $platforms->links() }}
</x-card>
@endsection
