<!doctype html>
<html class="admin-layout" lang="en" data-bs-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>@yield('title', 'Administration') — DevNiox</title>@vite(['resources/css/admin.css', 'resources/js/admin.js'])</head>
<body class="layout-fixed sidebar-expand-lg bg-body-tertiary"><a class="skip-link btn btn-primary" href="#admin-main">Skip to content</a><div class="app-wrapper">
<nav class="app-header navbar navbar-expand bg-body"><div class="container-fluid"><button class="nav-link" type="button" data-lte-toggle="sidebar" aria-label="Toggle sidebar"><i class="bi bi-list" aria-hidden="true"></i></button><ul class="navbar-nav ms-auto">
<li class="nav-item dropdown"><a class="nav-link" data-bs-toggle="dropdown" href="#" aria-label="{{ $unreadNotificationCount ?? 0 }} unread notifications"><i class="bi bi-bell" aria-hidden="true"></i>@if(($unreadNotificationCount ?? 0) > 0)<span class="navbar-badge badge text-bg-danger">{{ $unreadNotificationCount }}</span>@endif</a><div class="dropdown-menu dropdown-menu-lg dropdown-menu-end"><span class="dropdown-item dropdown-header">{{ $unreadNotificationCount ?? 0 }} unread</span>@forelse(($navbarNotifications ?? []) as $note)<form method="post" action="{{ route('admin.notifications.read', $note) }}">@csrf @method('PATCH')<button class="dropdown-item text-wrap" type="submit"><strong>{{ $note->title }}</strong><br><small>{{ Str::limit($note->message, 70) }}</small></button></form>@empty<span class="dropdown-item text-muted">No notifications</span>@endforelse<a class="dropdown-item dropdown-footer" href="{{ route('admin.notifications.index') }}">View all</a></div></li>
<li class="nav-item"><button class="nav-link" type="button" data-theme-toggle aria-label="Toggle theme" aria-pressed="false"><i class="bi bi-circle-half" aria-hidden="true"></i></button></li><li class="nav-item dropdown"><a class="nav-link dropdown-toggle d-flex align-items-center gap-2" data-bs-toggle="dropdown" href="#">@if(auth()->user()->avatar_path)<img class="navbar-avatar" src="{{ asset('storage/'.auth()->user()->avatar_path) }}" alt="" width="28" height="28">@endif<span>{{ auth()->user()->name }}</span></a><div class="dropdown-menu dropdown-menu-end"><a class="dropdown-item" href="{{ route('admin.profile.show') }}"><i class="bi bi-person-circle me-2" aria-hidden="true"></i>My Profile</a><div class="dropdown-divider"></div><form method="post" action="{{ route('logout') }}">@csrf<button class="dropdown-item" type="submit"><i class="bi bi-box-arrow-right me-2" aria-hidden="true"></i>Sign out</button></form></div></li>
</ul></div></nav>
<aside class="app-sidebar shadow" data-bs-theme="dark"><div class="sidebar-brand"><a href="{{ route('admin.dashboard') }}" class="brand-link"><span class="brand-text fw-bold">DevNiox</span></a></div><div class="sidebar-wrapper"><nav class="mt-2" aria-label="Administration"><ul class="nav sidebar-menu flex-column" data-lte-toggle="treeview">
@can('access','dashboard.view')<li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.dashboard') ? 'active' : '' }}" href="{{ route('admin.dashboard') }}" @if(request()->routeIs('admin.dashboard')) aria-current="page" @endif><i class="nav-icon bi bi-speedometer2" aria-hidden="true"></i><p>Dashboard</p></a></li>@endcan
<li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.notifications.*') ? 'active' : '' }}" href="{{ route('admin.notifications.index') }}" @if(request()->routeIs('admin.notifications.*')) aria-current="page" @endif><i class="nav-icon bi bi-bell" aria-hidden="true"></i><p>Notifications</p></a></li>
@can('access','leads.view')<li class="nav-header">COMMUNICATION</li>
<li class="nav-item {{ request()->routeIs('admin.leads.*','admin.contact-messages.*','admin.demo-requests.*','admin.quote-requests.*') ? 'menu-open' : '' }}"><a class="nav-link {{ request()->routeIs('admin.leads.*','admin.contact-messages.*','admin.demo-requests.*','admin.quote-requests.*') ? 'active' : '' }}" href="#"><i class="nav-icon bi bi-chat-square-dots" aria-hidden="true"></i><p>Communication<i class="nav-arrow bi bi-chevron-right" aria-hidden="true"></i></p></a><ul class="nav nav-treeview"><li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.leads.*') && request()->routeIs('admin.leads.index') ? 'active' : '' }}" href="{{ route('admin.leads.index') }}"><i class="nav-icon bi bi-circle" aria-hidden="true"></i><p>All Communications</p></a></li><li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.contact-messages.*') ? 'active' : '' }}" href="{{ route('admin.contact-messages.index') }}"><i class="nav-icon bi bi-circle" aria-hidden="true"></i><p>Contact Messages</p></a></li><li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.demo-requests.*') ? 'active' : '' }}" href="{{ route('admin.demo-requests.index') }}"><i class="nav-icon bi bi-circle" aria-hidden="true"></i><p>Demo Requests</p></a></li><li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.quote-requests.*') ? 'active' : '' }}" href="{{ route('admin.quote-requests.index') }}"><i class="nav-icon bi bi-circle" aria-hidden="true"></i><p>Quote Requests</p></a></li></ul></li>@endcan
<li class="nav-header">OPERATIONS</li>
<li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.media.*') ? 'active' : '' }}" href="{{ route('admin.media.index') }}" @if(request()->routeIs('admin.media.*')) aria-current="page" @endif><i class="nav-icon bi bi-images" aria-hidden="true"></i><p>Media Library</p></a></li>
@can('access','orders.view')<li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.orders.*') ? 'active' : '' }}" href="{{ route('admin.orders.index') }}" @if(request()->routeIs('admin.orders.*')) aria-current="page" @endif><i class="nav-icon bi bi-kanban" aria-hidden="true"></i><p>Orders</p></a></li>@endcan
@can('access','finance.view')<li class="nav-item {{ request()->routeIs('admin.finance.*') ? 'menu-open' : '' }}"><a class="nav-link {{ request()->routeIs('admin.finance.*') ? 'active' : '' }}" href="#"><i class="nav-icon bi bi-cash-stack" aria-hidden="true"></i><p>Finance<i class="nav-arrow bi bi-chevron-right" aria-hidden="true"></i></p></a><ul class="nav nav-treeview"><li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.finance.transactions.*') ? 'active' : '' }}" href="{{ route('admin.finance.transactions.index') }}"><i class="nav-icon bi bi-circle" aria-hidden="true"></i><p>Money Management</p></a></li><li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.finance.reports.*') ? 'active' : '' }}" href="{{ route('admin.finance.reports.index') }}"><i class="nav-icon bi bi-circle" aria-hidden="true"></i><p>Reports</p></a></li><li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.finance.income-categories.*') ? 'active' : '' }}" href="{{ route('admin.finance.income-categories.index') }}"><i class="nav-icon bi bi-circle" aria-hidden="true"></i><p>Income Categories</p></a></li><li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.finance.expense-categories.*') ? 'active' : '' }}" href="{{ route('admin.finance.expense-categories.index') }}"><i class="nav-icon bi bi-circle" aria-hidden="true"></i><p>Expense Categories</p></a></li></ul></li>@endcan
<li class="nav-header">WEBSITE</li>@foreach(['home'=>'Home','about'=>'About','contact'=>'Contact'] as $key=>$label)<li class="nav-item"><a class="nav-link" href="{{ route('admin.cms.pages.edit',$key) }}"><i class="nav-icon bi bi-file-earmark-text" aria-hidden="true"></i><p>{{ $label }}</p></a></li>@endforeach<li class="nav-item"><a class="nav-link" href="{{ route('admin.platforms.index') }}"><i class="nav-icon bi bi-grid-3x3-gap" aria-hidden="true"></i><p>Platforms</p></a></li><li class="nav-item"><a class="nav-link" href="{{ route('admin.cms.navigation.edit') }}"><i class="nav-icon bi bi-list" aria-hidden="true"></i><p>Navigation</p></a></li><li class="nav-item"><a class="nav-link" href="{{ route('admin.cms.footer.edit') }}"><i class="nav-icon bi bi-layout-text-window-reverse" aria-hidden="true"></i><p>Footer</p></a></li><li class="nav-header">CONTENT</li>
@can('access','products.view')<li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.products.*') ? 'active' : '' }}" href="{{ route('admin.products.index') }}" @if(request()->routeIs('admin.products.*')) aria-current="page" @endif><i class="nav-icon bi bi-box-seam" aria-hidden="true"></i><p>Products</p></a></li>@endcan
@can('access','services.view')<li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.services.*') ? 'active' : '' }}" href="{{ route('admin.services.index') }}" @if(request()->routeIs('admin.services.*')) aria-current="page" @endif><i class="nav-icon bi bi-briefcase" aria-hidden="true"></i><p>Services</p></a></li>@endcan
@can('access','blog.view')<li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.blog.*') ? 'active' : '' }}" href="{{ route('admin.blog.index') }}"><i class="nav-icon bi bi-journal-richtext" aria-hidden="true"></i><p>Blog</p></a></li>@endcan
@can('access','portfolio.view')<li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.portfolio.*') ? 'active' : '' }}" href="{{ route('admin.portfolio.index') }}" @if(request()->routeIs('admin.portfolio.*')) aria-current="page" @endif><i class="nav-icon bi bi-images" aria-hidden="true"></i><p>Portfolio</p></a></li>@endcan
@if(auth()->user()->isAdmin())<li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.product-categories.*') ? 'active' : '' }}" href="{{ route('admin.product-categories.index') }}" @if(request()->routeIs('admin.product-categories.*')) aria-current="page" @endif><i class="nav-icon bi bi-tags" aria-hidden="true"></i><p>Product Categories</p></a></li>@endif
@if(auth()->user()->isAdmin())<li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.service-categories.*') ? 'active' : '' }}" href="{{ route('admin.service-categories.index') }}" @if(request()->routeIs('admin.service-categories.*')) aria-current="page" @endif><i class="nav-icon bi bi-tags" aria-hidden="true"></i><p>Service Categories</p></a></li>@endif
@if(auth()->user()->isAdmin())<li class="nav-item"><a class="nav-link" href="{{ route('admin.blog-categories.index') }}"><i class="nav-icon bi bi-folder" aria-hidden="true"></i><p>Blog Categories</p></a></li><li class="nav-item"><a class="nav-link" href="{{ route('admin.blog-tags.index') }}"><i class="nav-icon bi bi-tags" aria-hidden="true"></i><p>Blog Tags</p></a></li>@endif
@if(auth()->user()->isAdmin())<li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.portfolio-categories.*') ? 'active' : '' }}" href="{{ route('admin.portfolio-categories.index') }}" @if(request()->routeIs('admin.portfolio-categories.*')) aria-current="page" @endif><i class="nav-icon bi bi-tags" aria-hidden="true"></i><p>Portfolio Categories</p></a></li>@endif
@can('access','website-settings.view')<li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.settings.*') ? 'active' : '' }}" href="{{ route('admin.settings.edit') }}" @if(request()->routeIs('admin.settings.*')) aria-current="page" @endif><i class="nav-icon bi bi-gear" aria-hidden="true"></i><p>Website Settings</p></a></li>@endcan
@can('access','users.view')<li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.users.*') ? 'active' : '' }}" href="{{ route('admin.users.index') }}"><i class="nav-icon bi bi-people" aria-hidden="true"></i><p>Users</p></a></li>@endcan
@can('access','roles.view')<li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.roles.*','admin.permissions.*') ? 'active' : '' }}" href="{{ route('admin.roles.index') }}"><i class="nav-icon bi bi-shield-lock" aria-hidden="true"></i><p>Roles & Permissions</p></a></li>@endcan
@if(auth()->user()->isAdmin())<li class="nav-item"><a class="nav-link {{ request()->routeIs('admin.activity-logs.*') ? 'active' : '' }}" href="{{ route('admin.activity-logs.index') }}" @if(request()->routeIs('admin.activity-logs.*')) aria-current="page" @endif><i class="nav-icon bi bi-clock-history" aria-hidden="true"></i><p>Activity Log</p></a></li>@endif
<li class="nav-item"><a class="nav-link" href="{{ route('home') }}" target="_blank" rel="noopener"><i class="nav-icon bi bi-box-arrow-up-right" aria-hidden="true"></i><p>View website</p></a></li>
</ul></nav></div></aside>
<main class="app-main" id="admin-main"><div class="app-content-header"><div class="container-fluid"><div class="row align-items-center"><div class="col"><h1 class="mb-0">@yield('heading')</h1></div><div class="col-auto"><nav aria-label="Breadcrumb"><ol class="breadcrumb mb-0"><li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Admin</a></li><li class="breadcrumb-item active" aria-current="page">@yield('heading')</li></ol></nav></div></div></div></div><div class="app-content"><div class="container-fluid">
@if(session('success'))<x-alert type="success">{{ session('success') }}</x-alert>@endif
@if($errors->any())<x-alert type="danger"><p class="visually-hidden">Please correct the following errors.</p><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></x-alert>@endif
@yield('content')</div></div></main><footer class="app-footer">DevNiox production foundation</footer></div></body></html>

