@extends('layouts.app')
@section('title',$cmsPage->meta_title?:($siteSettings['seo.meta_title']??$cmsPage->about->hero_heading))
@section('description',$cmsPage->meta_description?:($siteSettings['seo.meta_description']??$cmsPage->about->hero_description))
@section('canonical',$cmsPage->canonical_url?:route('about'))
@push('head')@unless($cmsPage->is_indexable)<meta name="robots" content="noindex,nofollow">@endunless @if($cmsPage->open_graph_image_path)<meta property="og:image" content="{{ url(Storage::url($cmsPage->open_graph_image_path)) }}">@endif @endpush
@section('content')
@php
    $about = $cmsPage->about;
    $copy = static fn ($value, $fallback, array $seedCopy = []) => blank($value) ? $fallback : $value;
    $heroHeading = $copy($about->hero_heading, 'We build the software behind daily business operations.', ['Engineering with intent.']);
    $heroDescription = $copy($about->hero_description, 'DevNiox is an engineering company focused on ERP, order management, financial workflows, business automation, and AI-assisted systems for organisations that need dependable software ownership.', ['We combine product thinking, strong architecture, and measured execution.']);
    $storyTitle = $copy($about->story_title, 'DevNiox began with a practical engineering question.', ['Our story']);
    $storyDescription = $copy($about->story_description, 'Why should growing businesses have to choose between rigid off-the-shelf tools and fragile custom projects? DevNiox was founded to build a stronger middle ground: commercial products with clear operational purpose, and custom systems engineered with the same discipline. We start with the work people perform, the decisions they make, and the information the business must trust. The result is software designed for ownership—not merely launch.', ['DevNiox creates dependable digital systems.']);
    $missionTitle = $copy($about->mission_title, 'Make complex operations easier to control.', ['Our mission']);
    $missionDescription = $copy($about->mission_description, 'Translate business rules into understandable, secure, and maintainable software that reduces manual coordination and improves decision quality.', ['Create useful technology.']);
    $visionTitle = $copy($about->vision_title, 'Become the product engineering partner behind durable businesses.', ['Our vision']);
    $visionDescription = $copy($about->vision_description, 'Build a portfolio of operational software and long-term engineering relationships where each release increases clarity, capability, and business resilience.', ['Excellent digital systems for ambitious organisations.']);
    $values = $cmsPage->coreValues->isNotEmpty() ? $cmsPage->coreValues : collect([(object)['title'=>'Model the business honestly','description'=>'Good systems represent real roles, exceptions, approvals, and accountability instead of hiding complexity behind attractive screens.'],(object)['title'=>'Prefer explicit architecture','description'=>'Data ownership, permissions, integrations, and failure behaviour should be understandable to the people responsible for the product.'],(object)['title'=>'Release with evidence','description'=>'Validation, tests, review criteria, deployment checks, and documentation turn confidence into something that can be verified.']]);
    $work = $cmsPage->workItems->isNotEmpty() ? $cmsPage->workItems : collect([(object)['title'=>'Understand the operation','description'=>'Clarify users, workflows, risks, constraints, and the business measure that should change.'],(object)['title'=>'Define the product boundary','description'=>'Prioritise the smallest coherent system and document what it owns, connects to, and leaves outside.'],(object)['title'=>'Build in reviewable increments','description'=>'Keep business and technical stakeholders close to working software and explicit acceptance criteria.'],(object)['title'=>'Operate and improve','description'=>'Use adoption, support, performance, and workflow evidence to guide the next release.']]);
@endphp
<header class="about-hero" data-cms-heading="{{ $about->hero_heading }}" @if($about->hero_banner_path)style="--hero-image:url('{{ Storage::url($about->hero_banner_path) }}')"@endif><div class="container"><div class="about-hero-grid"><div><p class="eyebrow">{{ $about->hero_label ?: 'About DevNiox' }}</p><h1>{{ $heroHeading }}</h1></div><div class="about-manifesto"><span></span><p>{{ $heroDescription }}</p><a href="{{ route('contact', [], false) }}">{{ $about->hero_cta_text ?: 'Start a conversation' }} <i class="bi bi-arrow-right"></i></a></div></div></div></header>
<section class="story-chapter"><div class="container"><div class="story-number">01</div><div class="row g-5 align-items-center"><div class="col-lg-6"><p class="eyebrow">{{ $about->story_label ?: 'Company story' }}</p><h2>{{ $storyTitle }}</h2><div class="story-copy">{!! nl2br(e($storyDescription)) !!}</div></div><div class="col-lg-6">@if($cmsPage->about->story_image_path)<img src="{{ Storage::url($cmsPage->about->story_image_path) }}" alt="{{ $storyTitle }}" width="900" height="700">@else<div class="belief-graphic" aria-hidden="true"><span>Think</span><i></i><span>Build</span><i></i><span>Learn</span></div>@endif</div></div></div></section>
<section class="direction-section"><div class="container"><div class="direction-grid"><article><span>02 / Mission</span><h2>{{ $missionTitle }}</h2><p>{{ $missionDescription }}</p></article><article><span>03 / Vision</span><h2>{{ $visionTitle }}</h2><p>{{ $visionDescription }}</p></article></div></div></section>
<section class="philosophy-section"><div class="container"><div class="philosophy-intro"><p class="eyebrow">{{ $about->philosophy_label ?: 'Technology philosophy' }}</p><h2>{{ $about->philosophy_title ?: 'Principles behind the systems we build.' }}</h2></div><div class="philosophy-list">@foreach($values as $item)<article><span>{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</span><div><h3>{{ $item->title }}</h3><p>{{ $item->description }}</p></div></article>@endforeach</div></div></section>
<section class="process-section"><div class="container"><div class="process-heading"><p class="eyebrow">{{ $about->process_label ?: 'Why DevNiox' }}</p><h2>{{ $about->process_title ?: 'A development process grounded in trust.' }}</h2></div><ol class="about-process">@foreach($work as $item)<li><span>{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</span><h3>{{ $item->title }}</h3><p>{{ $item->description }}</p></li>@endforeach</ol></div></section>
@endsection

