@extends('layouts.app')
@section('title',$cmsPage->meta_title?:($siteSettings['seo.meta_title']??'DevNiox'))
@section('description',$cmsPage->meta_description?:($siteSettings['seo.meta_description']??''))
@section('canonical',$cmsPage->canonical_url?:route('home'))
@push('head')@unless($cmsPage->is_indexable)<meta name="robots" content="noindex,nofollow">@endunless @endpush
@section('content')
@php
    $home = $cmsPage->home;
    $copy = static fn ($value, $fallback, array $seedCopy = []) => blank($value) ? $fallback : $value;
    $heroEyebrow = $copy($home->hero_subheading, 'Enterprise software for operational teams', ['Software · AI · Growth']);
    $heroHeading = $copy($home->hero_heading, 'We build the software businesses run on.', ['We engineer digital advantage.']);
    $heroDescription = $copy($home->hero_description, 'DevNiox designs commercial software products, ERP workflows, order and money management systems, and AI-assisted operations for growing companies that need dependable technology ownership.', ['DevNiox designs dependable software, intelligent systems, and digital products built to scale with your business.']);
    $introTitle = $copy($home->intro_title, 'Product engineering for work that cannot afford guesswork.', ['Engineering built around outcomes']);
    $introDescription = $copy($home->intro_description, 'We turn operational rules, approvals, reporting needs, and integration constraints into software teams can understand, adopt, and extend.', ['We combine product thinking, sound architecture, and disciplined execution.']);
    $publicCtaUrl = static function (?string $url, string $fallbackRoute): string {
        $path = parse_url((string) $url, PHP_URL_PATH);
        $routes = ['/contact' => 'contact', '/products' => 'products', '/services' => 'services', '/portfolio' => 'portfolio', '/blog' => 'blog', '/about' => 'about', '/request-demo' => 'demo-request', '/request-quote' => 'quote-request'];

        return route($routes[$path] ?? $fallbackRoute, [], false);
    };
    $primaryCtaUrl = $publicCtaUrl($home->primary_button_url, 'contact');
    $secondaryCtaUrl = $publicCtaUrl($home->secondary_button_url, 'contact');
    $whyItems = $cmsPage->whyItems->isNotEmpty() ? $cmsPage->whyItems : collect([(object)['title'=>'Product ownership, not project hand-off','description'=>'Architecture, releases, documentation, and maintainability are considered together so the system remains operable after launch.'],(object)['title'=>'Workflows modelled before screens','description'=>'We clarify roles, decisions, exceptions, and data movement before implementation, reducing expensive corrections late in delivery.'],(object)['title'=>'Evidence built into delivery','description'=>'Acceptance criteria, validation, testing, and production checks make progress reviewable by technical and business stakeholders.']]);
@endphp
<section class="home-hero" @if($cmsPage->home->hero_background_path)style="--hero-image:url('{{ Storage::url($cmsPage->home->hero_background_path) }}')"@endif>
    <div class="hero-orb hero-orb-one" aria-hidden="true"></div><div class="hero-orb hero-orb-two" aria-hidden="true"></div>
    <div class="container position-relative"><div class="row align-items-center g-5">
        <div class="col-lg-6 hero-copy" data-reveal>
            <p class="hero-badge"><span></span>{{ $heroEyebrow }}</p>
            <h1>{{ $heroHeading }}</h1>
            <p class="hero-lead">{{ $heroDescription }}</p>
            <div class="hero-actions">@if($cmsPage->home->primary_button_text)<a class="btn btn-primary btn-lg" href="{{ $primaryCtaUrl }}">{{ $cmsPage->home->primary_button_text }} <i class="bi bi-arrow-right" aria-hidden="true"></i></a>@endif @if($cmsPage->home->secondary_button_text)<a class="btn btn-outline-secondary btn-lg" href="{{ $secondaryCtaUrl }}">{{ $cmsPage->home->secondary_button_text }}</a>@endif</div>
            <ul class="trust-list" aria-label="DevNiox capabilities"><li><i class="bi bi-check-circle-fill" aria-hidden="true"></i> ERP and operations</li><li><i class="bi bi-check-circle-fill" aria-hidden="true"></i> Order and finance workflows</li><li><i class="bi bi-check-circle-fill" aria-hidden="true"></i> AI-assisted systems</li><li><i class="bi bi-check-circle-fill" aria-hidden="true"></i> Long-term product ownership</li></ul>
        </div>
        <div class="col-lg-6" data-reveal><div class="software-showcase" aria-label="Enterprise software interface preview">
            <div class="showcase-window main-window"><div class="window-bar"><span></span><span></span><span></span><small>DevNiox Business Suite</small></div><div class="dashboard-shell"><aside aria-hidden="true"><b>D</b><i class="bi bi-grid"></i><i class="bi bi-box-seam"></i><i class="bi bi-people"></i><i class="bi bi-bar-chart"></i></aside><div class="dashboard-main"><div class="dashboard-top"><div><small>Operations overview</small><strong>Business dashboard</strong></div><span class="avatar">DN</span></div><div class="metric-grid"><div><small>Software products</small><b><i class="bi bi-box-seam"></i></b><em class="positive">Release managed</em></div><div><small>Portfolio delivery</small><b><i class="bi bi-kanban"></i></b><em>Outcome measured</em></div><div><small>Enterprise services</small><b><i class="bi bi-building-gear"></i></b><em class="positive">Outcome scoped</em></div></div><div class="chart-card"><div class="chart-heading"><span>Performance</span><small>Live overview</small></div><div class="chart-bars" aria-hidden="true"><i style="height:38%"></i><i style="height:54%"></i><i style="height:44%"></i><i style="height:72%"></i><i style="height:64%"></i><i style="height:88%"></i><i style="height:78%"></i></div></div></div></div></div>
            <div class="floating-panel panel-orders"><i class="bi bi-box-seam"></i><span><small>Product systems</small><strong>Release managed</strong></span></div><div class="floating-panel panel-ai"><i class="bi bi-stars"></i><span><small>AI assistant</small><strong>Automation active</strong></span></div><div class="floating-panel panel-growth"><span class="pulse-dot"></span><div><small>System status</small><strong>Production monitored</strong></div></div>
        </div></div>
    </div></div>
</section>

<section class="company-intro page-section"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-7" data-reveal><p class="eyebrow">What DevNiox builds</p><h2>{{ $introTitle }}</h2><p class="section-lead">{{ $introDescription }}</p></div>@if($cmsPage->home->intro_image_path)<div class="col-lg-5" data-reveal><img class="intro-image" src="{{ Storage::url($cmsPage->home->intro_image_path) }}" alt="{{ $cmsPage->home->intro_title }}"></div>@else<div class="col-lg-5" data-reveal><div class="capability-stack"><span><i class="bi bi-diagram-3"></i> ERP and operational workflows</span><span><i class="bi bi-receipt"></i> Orders, billing, and money management</span><span><i class="bi bi-cpu"></i> AI-assisted business automation</span></div></div>@endif</div></div></section>

@if($featuredProducts->isNotEmpty())<section class="page-section product-priority-section"><div class="container"><div class="section-heading" data-reveal><div><p class="eyebrow">Flagship software</p><h2>{{ $cmsPage->home->products_title }}</h2><p>{{ $cmsPage->home->products_description }}</p></div><a class="section-link" href="{{ route('products') }}">Explore all products <i class="bi bi-arrow-right"></i></a></div><div class="row g-4">@foreach($featuredProducts as $product)<div class="col-md-6 col-xl-4" data-reveal><x-product-card :product="$product" /></div>@endforeach</div></div></section>@endif

@if($featuredServices->isNotEmpty())<section class="page-section"><div class="container"><div class="section-heading" data-reveal><div><p class="eyebrow">Enterprise delivery</p><h2>{{ $cmsPage->home->services_title }}</h2><p>{{ $cmsPage->home->services_description }}</p></div><a class="section-link" href="{{ route('services') }}">View capabilities <i class="bi bi-arrow-right"></i></a></div><div class="row g-4">@foreach($featuredServices as $service)<div class="col-md-6 col-xl-4" data-reveal><x-service-card :service="$service" /></div>@endforeach</div></div></section>@endif



<section class="page-section why-section"><div class="container"><div class="row g-5"><div class="col-lg-5" data-reveal><p class="eyebrow">Why DevNiox</p><h2>Decisions that survive production, growth, and handover.</h2><p class="section-lead">The work is organised around business rules and software ownership—not a queue of disconnected feature requests.</p>@if($cmsPage->statistics->isNotEmpty())<div class="stats-grid">@foreach($cmsPage->statistics as $item)<div><strong data-counter>{{ $item->value }}</strong><span>{{ $item->title }}</span></div>@endforeach</div>@endif</div><div class="col-lg-7"><div class="why-list">@foreach($whyItems as $item)<article data-reveal><span>{{ str_pad($loop->iteration, 2, '0', STR_PAD_LEFT) }}</span><div><h3>{{ $item->title }}</h3><p>{{ $item->description }}</p></div></article>@endforeach</div></div></div></div></section>

<section class="page-section home-industries"><div class="container"><div class="section-heading"><div><p class="eyebrow">Industries we serve</p><h2>Operations with real rules, roles, and consequences.</h2><p>Our strongest fit is where software coordinates people, transactions, inventory, service delivery, or management reporting.</p></div></div><div class="industry-strip"><article><i class="bi bi-shop"></i><h3>Retail &amp; distribution</h3><p>Orders, inventory visibility, customer records, purchasing, and financial control.</p></article><article><i class="bi bi-cup-hot"></i><h3>Hospitality &amp; restaurants</h3><p>QR ordering, menu operations, fulfilment, outlet workflows, and performance reporting.</p></article><article><i class="bi bi-building"></i><h3>Professional operations</h3><p>Clients, projects, approvals, documents, billing, and management information in one workflow.</p></article><article><i class="bi bi-graph-up-arrow"></i><h3>Growing businesses</h3><p>Replace fragile spreadsheets and disconnected tools with controlled, measurable processes.</p></article></div></div></section>
<section class="page-section home-process"><div class="container"><div class="section-heading"><div><p class="eyebrow">Development process</p><h2>From operating problem to maintainable product.</h2><p>Each stage produces decisions and evidence that the next stage can rely on.</p></div></div><ol class="home-process-list">@foreach([['Discover','Map the business objective, users, constraints, integrations, and measures of success.'],['Design','Define workflows, information architecture, technical boundaries, and delivery priorities.'],['Engineer','Build in reviewable increments with validation, testing, and deployment readiness included.'],['Operate','Measure adoption, resolve friction, and plan improvements against operational evidence.']] as [$title,$description])<li><span>{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</span><h3>{{ $title }}</h3><p>{{ $description }}</p></li>@endforeach</ol></div></section>
<section class="page-section home-technology"><div class="container"><div class="row g-5 align-items-center"><div class="col-lg-5"><p class="eyebrow">Technology we use</p><h2>Conventional foundations. Deliberate intelligence.</h2><p class="section-lead">Laravel, PHP, relational data, accessible web interfaces, automated testing, and carefully bounded AI integrations form a stack that can be operated and extended.</p></div><div class="col-lg-7"><div class="technology-principles"><article><strong>Relational by design</strong><span>Business data keeps explicit relationships, constraints, and ownership.</span></article><article><strong>Web-native delivery</strong><span>Responsive interfaces work across devices without unnecessary client-side complexity.</span></article><article><strong>Automation with controls</strong><span>AI and workflow automation support decisions while permissions and review remain clear.</span></article><article><strong>Release-ready engineering</strong><span>Validation, tests, deployment configuration, and recovery concerns are part of delivery.</span></article></div></div></div></div></section>
@if($featuredPortfolio->isNotEmpty())<section class="page-section"><div class="container"><div class="section-heading" data-reveal><div><p class="eyebrow">Proven delivery</p><h2>{{ $cmsPage->home->portfolio_title }}</h2><p>{{ $cmsPage->home->portfolio_description }}</p></div><a class="section-link" href="{{ route('portfolio') }}">See our work <i class="bi bi-arrow-right"></i></a></div><div class="row g-4">@foreach($featuredPortfolio as $project)<div class="col-md-6 col-xl-4" data-reveal><x-portfolio-card :project="$project" /></div>@endforeach</div></div></section>@endif

<section class="page-section home-faq"><div class="container col-xl-9"><div class="section-heading"><div><p class="eyebrow">Frequently asked questions</p><h2>What business and technical teams usually ask first.</h2></div></div><div class="accordion" id="home-faq">@foreach([['Can we evaluate a product before committing?','Yes. A guided demo focuses on your users, current workflow, required controls, and deployment questions—not a generic feature tour.'],['When is custom software the right choice?','Custom development is appropriate when the workflow creates operational value and standard tools force costly workarounds, duplicated data, or weak control.'],['Can DevNiox integrate with existing systems?','Integration is assessed during discovery. We document data ownership, authentication, failure handling, and reconciliation needs before committing to an approach.'],['What information helps you prepare a useful proposal?','Share the business objective, primary users, current process, known integrations, timing constraints, and the result you need to measure.']] as [$question,$answer])<div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button @unless($loop->first) collapsed @endunless" type="button" data-bs-toggle="collapse" data-bs-target="#home-faq-{{ $loop->iteration }}" aria-expanded="{{ $loop->first ? 'true' : 'false' }}">{{ $question }}</button></h3><div id="home-faq-{{ $loop->iteration }}" class="accordion-collapse collapse @if($loop->first) show @endif" data-bs-parent="#home-faq"><div class="accordion-body">{{ $answer }}</div></div></div>@endforeach</div></div></section>
@if($latestPosts->isNotEmpty())<section class="page-section articles-section"><div class="container"><div class="section-heading" data-reveal><div><p class="eyebrow">Knowledge center</p><h2>{{ $cmsPage->home->articles_title }}</h2><p>{{ $cmsPage->home->articles_description }}</p></div><a class="section-link" href="{{ route('blog') }}">Read all articles <i class="bi bi-arrow-right"></i></a></div><div class="row g-4">@foreach(($featuredPosts->isNotEmpty()?$featuredPosts:$latestPosts->take(3)) as $post)<div class="col-md-6 col-xl-4" data-reveal><x-blog-card :post="$post"/></div>@endforeach</div></div></section>@endif

@if(($home->ecosystem_enabled ?? true) && $platforms->isNotEmpty())<section class="page-section ecosystem-section"><div class="container"><div class="section-heading" data-reveal><div><p class="eyebrow">{{ $home->ecosystem_label }}</p><h2>{{ $home->ecosystem_title }}</h2><p>{{ $home->ecosystem_description }}</p></div></div><div class="ecosystem-grid">@foreach($platforms as $platform)<article class="ecosystem-card" data-reveal @if($platform->brand_color)style="--platform-color: {{ $platform->brand_color }}"@endif><div class="ecosystem-logo">@if($platform->logo)<img src="{{ Storage::url($platform->logo) }}" alt="{{ $platform->name }} logo" loading="lazy">@else<span>{{ Str::of($platform->name)->substr(0,1)->upper() }}</span>@endif</div><div class="ecosystem-copy">@if($platform->badge)<span class="ecosystem-badge">{{ $platform->badge }}</span>@endif<h3>{{ $platform->name }}</h3><p>{{ $platform->description }}</p></div><a class="card-link" href="{{ $platform->website_url }}" @if($platform->open_in_new_tab)target="_blank" rel="noopener noreferrer"@endif>Visit Website <i class="bi bi-arrow-up-right" aria-hidden="true"></i></a></article>@endforeach</div><p class="ecosystem-note">{{ $home->ecosystem_note }}</p></div></section>@endif
@endsection


