@extends('layouts.app')
@section('title',$cmsPage->meta_title?:($siteSettings['seo.meta_title']??'DevNiox'))
@section('description',$cmsPage->meta_description?:($siteSettings['seo.meta_description']??''))
@section('canonical',$cmsPage->canonical_url?:route('home'))
@push('head')@unless($cmsPage->is_indexable)<meta name="robots" content="noindex,nofollow">@endunless @endpush
@section('content')
@php
    $home = $cmsPage->home;
    $copy = static fn ($value, $fallback, array $seedCopy = []) => blank($value) ? $fallback : $value;
    $heroEyebrow = $copy($home->hero_subheading, 'Enterprise software for operational teams', ['Software · AI · Growth']);
    $heroHeading = $copy($home->hero_heading, 'We build the software businesses run on.', ['We engineer digital advantage.']);
    $heroDescription = $copy($home->hero_description, 'DevNiox designs commercial software products, ERP workflows, order and money management systems, and AI-assisted operations for growing companies that need dependable technology ownership.', ['DevNiox designs dependable software, intelligent systems, and digital products built to scale with your business.']);
    $introTitle = $copy($home->intro_title, 'Product engineering for work that cannot afford guesswork.', ['Engineering built around outcomes']);
    $introDescription = $copy($home->intro_description, 'We turn operational rules, approvals, reporting needs, and integration constraints into software teams can understand, adopt, and extend.', ['We combine product thinking, sound architecture, and disciplined execution.']);
    $publicCtaUrl = static function (?string $url, string $fallbackRoute): string {
        $path = parse_url((string) $url, PHP_URL_PATH);
        $routes = ['/contact' => 'contact', '/products' => 'products', '/services' => 'services', '/portfolio' => 'portfolio', '/blog' => 'blog', '/about' => 'about', '/request-demo' => 'demo-request', '/request-quote' => 'quote-request'];

        return route($routes[$path] ?? $fallbackRoute, [], false);
    };
    $primaryCtaUrl = $publicCtaUrl($home->primary_button_url, 'contact');
    $secondaryCtaUrl = $publicCtaUrl($home->secondary_button_url, 'contact');
    $whyItems = $cmsPage->whyItems->isNotEmpty() ? $cmsPage->whyItems : collect([(object)['title'=>'Product ownership, not project hand-off','description'=>'Architecture, releases, documentation, and maintainability are considered together so the system remains operable after launch.'],(object)['title'=>'Workflows modelled before screens','description'=>'We clarify roles, decisions, exceptions, and data movement before implementation, reducing expensive corrections late in delivery.'],(object)['title'=>'Evidence built into delivery','description'=>'Acceptance criteria, validation, testing, and production checks make progress reviewable by technical and business stakeholders.']]);
    $trustItems = $cmsPage->trustItems->isNotEmpty() ? $cmsPage->trustItems : collect([(object)['title'=>'ERP and operations','icon'=>'check-circle-fill'],(object)['title'=>'Order and finance workflows','icon'=>'check-circle-fill'],(object)['title'=>'AI-assisted systems','icon'=>'check-circle-fill'],(object)['title'=>'Long-term product ownership','icon'=>'check-circle-fill']]);
    $industryItems = $cmsPage->industryItems->isNotEmpty() ? $cmsPage->industryItems : collect([(object)['title'=>'Retail & distribution','description'=>'Orders, inventory visibility, customer records, purchasing, and financial control.','icon'=>'shop'],(object)['title'=>'Hospitality & restaurants','description'=>'QR ordering, menu operations, fulfilment, outlet workflows, and performance reporting.','icon'=>'cup-hot'],(object)['title'=>'Professional operations','description'=>'Clients, projects, approvals, documents, billing, and management information in one workflow.','icon'=>'building'],(object)['title'=>'Growing businesses','description'=>'Replace fragile spreadsheets and disconnected tools with controlled, measurable processes.','icon'=>'graph-up-arrow']]);
    $processItems = $cmsPage->processItems->isNotEmpty() ? $cmsPage->processItems : collect([(object)['title'=>'Discover','description'=>'Map the business objective, users, constraints, integrations, and measures of success.'],(object)['title'=>'Design','description'=>'Define workflows, information architecture, technical boundaries, and delivery priorities.'],(object)['title'=>'Engineer','description'=>'Build in reviewable increments with validation, testing, and deployment readiness included.'],(object)['title'=>'Operate','description'=>'Measure adoption, resolve friction, and plan improvements against operational evidence.']]);
    $technologyItems = $cmsPage->technologyItems->isNotEmpty() ? $cmsPage->technologyItems : collect([(object)['title'=>'Relational by design','description'=>'Business data keeps explicit relationships, constraints, and ownership.'],(object)['title'=>'Web-native delivery','description'=>'Responsive interfaces work across devices without unnecessary client-side complexity.'],(object)['title'=>'Automation with controls','description'=>'AI and workflow automation support decisions while permissions and review remain clear.'],(object)['title'=>'Release-ready engineering','description'=>'Validation, tests, deployment configuration, and recovery concerns are part of delivery.']]);
    $faqItems = $cmsPage->faqItems->isNotEmpty() ? $cmsPage->faqItems : collect([(object)['title'=>'Can we evaluate a product before committing?','description'=>'Yes. A guided demo focuses on your users, current workflow, required controls, and deployment questions—not a generic feature tour.'],(object)['title'=>'When is custom software the right choice?','description'=>'Custom development is appropriate when the workflow creates operational value and standard tools force costly workarounds, duplicated data, or weak control.'],(object)['title'=>'Can DevNiox integrate with existing systems?','description'=>'Integration is assessed during discovery. We document data ownership, authentication, failure handling, and reconciliation needs before committing to an approach.'],(object)['title'=>'What information helps you prepare a useful proposal?','description'=>'Share the business objective, primary users, current process, known integrations, timing constraints, and the result you need to measure.']]);
@endphp
<section class="home-hero" @if($cmsPage->home->hero_background_path)style="--hero-image:url('{{ Storage::url($cmsPage->home->hero_background_path) }}')"@endif>
    <div class="hero-orb hero-orb-one" aria-hidden="true"></div><div class="hero-orb hero-orb-two" aria-hidden="true"></div>
    <div class="container position-relative"><div class="row align-items-center g-5">
        <div class="col-lg-6 hero-copy" data-reveal>
            <p class="hero-badge"><span></span>{{ $heroEyebrow }}</p>
            <h1>{{ $heroHeading }}</h1>
            <p class="hero-lead">{{ $heroDescription }}</p>
            <div class="hero-actions">@if($cmsPage->home->primary_button_text)<a class="btn btn-primary btn-lg" href="{{ $primaryCtaUrl }}">{{ $cmsPage->home->primary_button_text }} <i class="bi bi-arrow-right" aria-hidden="true"></i></a>@endif @if($cmsPage->home->secondary_button_text)<a class="btn btn-outline-secondary btn-lg" href="{{ $secondaryCtaUrl }}">{{ $cmsPage->home->secondary_button_text }}</a>@endif</div>
            <ul class="trust-list" aria-label="DevNiox capabilities">@foreach($trustItems as $item)<li><i class="bi bi-{{ $item->icon ?: 'check-circle-fill' }}" aria-hidden="true"></i> {{ $item->title }}</li>@endforeach</ul>
        </div>
        <div class="col-lg-6" data-reveal><div class="software-showcase" aria-label="{{ $home->hero_showcase_label ?: 'Enterprise software interface preview' }}">
            <div class="showcase-window main-window"><div class="window-bar"><span></span><span></span><span></span><small>{{ $home->hero_window_title ?: 'DevNiox Business Suite' }}</small></div><div class="dashboard-shell"><aside aria-hidden="true"><b>D</b><i class="bi bi-grid"></i><i class="bi bi-box-seam"></i><i class="bi bi-people"></i><i class="bi bi-bar-chart"></i></aside><div class="dashboard-main"><div class="dashboard-top"><div><small>{{ $home->hero_dashboard_label ?: 'Operations overview' }}</small><strong>{{ $home->hero_dashboard_title ?: 'Business dashboard' }}</strong></div><span class="avatar">DN</span></div><div class="metric-grid"><div><small>{{ $home->hero_metric_one_label ?: 'Software products' }}</small><b><i class="bi bi-box-seam"></i></b><em class="positive">{{ $home->hero_metric_one_status ?: 'Release managed' }}</em></div><div><small>{{ $home->hero_metric_two_label ?: 'Portfolio delivery' }}</small><b><i class="bi bi-kanban"></i></b><em>{{ $home->hero_metric_two_status ?: 'Outcome measured' }}</em></div><div><small>{{ $home->hero_metric_three_label ?: 'Enterprise services' }}</small><b><i class="bi bi-building-gear"></i></b><em class="positive">{{ $home->hero_metric_three_status ?: 'Outcome scoped' }}</em></div></div><div class="chart-card"><div class="chart-heading"><span>{{ $home->hero_chart_title ?: 'Performance' }}</span><small>{{ $home->hero_chart_label ?: 'Live overview' }}</small></div><div class="chart-bars" aria-hidden="true"><i style="height:38%"></i><i style="height:54%"></i><i style="height:44%"></i><i style="height:72%"></i><i style="height:64%"></i><i style="height:88%"></i><i style="height:78%"></i></div></div></div></div></div>
            <div class="floating-panel panel-orders"><i class="bi bi-box-seam"></i><span><small>{{ $home->hero_floating_one_label ?: 'Product systems' }}</small><strong>{{ $home->hero_floating_one_title ?: 'Release managed' }}</strong></span></div><div class="floating-panel panel-ai"><i class="bi bi-stars"></i><span><small>{{ $home->hero_floating_two_label ?: 'AI assistant' }}</small><strong>{{ $home->hero_floating_two_title ?: 'Automation active' }}</strong></span></div><div class="floating-panel panel-growth"><span class="pulse-dot"></span><div><small>{{ $home->hero_floating_three_label ?: 'System status' }}</small><strong>{{ $home->hero_floating_three_title ?: 'Production monitored' }}</strong></div></div>
        </div></div>
    </div></div>
</section>

<section class="company-intro page-section"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-7" data-reveal><p class="eyebrow">{{ $home->intro_label ?: 'What DevNiox builds' }}</p><h2>{{ $introTitle }}</h2><p class="section-lead">{{ $introDescription }}</p></div>@if($cmsPage->home->intro_image_path)<div class="col-lg-5" data-reveal><img class="intro-image" src="{{ Storage::url($cmsPage->home->intro_image_path) }}" alt="{{ $cmsPage->home->intro_title }}"></div>@else<div class="col-lg-5" data-reveal><div class="capability-stack"><span><i class="bi bi-diagram-3"></i> ERP and operational workflows</span><span><i class="bi bi-receipt"></i> Orders, billing, and money management</span><span><i class="bi bi-cpu"></i> AI-assisted business automation</span></div></div>@endif</div></div></section>

@if($featuredProducts->isNotEmpty())<section class="page-section product-priority-section"><div class="container"><div class="section-heading" data-reveal><div><p class="eyebrow">{{ $home->products_label ?: 'Flagship software' }}</p><h2>{{ $cmsPage->home->products_title }}</h2><p>{{ $cmsPage->home->products_description }}</p></div><a class="section-link" href="{{ route('products') }}">{{ $home->products_link_text ?: 'Explore all products' }} <i class="bi bi-arrow-right"></i></a></div><div class="row g-4">@foreach($featuredProducts as $product)<div class="col-md-6 col-xl-4" data-reveal><x-product-card :product="$product" /></div>@endforeach</div></div></section>@endif

@if($featuredServices->isNotEmpty())<section class="page-section"><div class="container"><div class="section-heading" data-reveal><div><p class="eyebrow">{{ $home->services_label ?: 'Enterprise delivery' }}</p><h2>{{ $cmsPage->home->services_title }}</h2><p>{{ $cmsPage->home->services_description }}</p></div><a class="section-link" href="{{ route('services') }}">{{ $home->services_link_text ?: 'View capabilities' }} <i class="bi bi-arrow-right"></i></a></div><div class="row g-4">@foreach($featuredServices as $service)<div class="col-md-6 col-xl-4" data-reveal><x-service-card :service="$service" /></div>@endforeach</div></div></section>@endif



<section class="page-section why-section"><div class="container"><div class="row g-5"><div class="col-lg-5" data-reveal><p class="eyebrow">{{ $home->why_label ?: 'Why DevNiox' }}</p><h2>{{ $home->why_title ?: 'Decisions that survive production, growth, and handover.' }}</h2><p class="section-lead">{{ $home->why_description ?: 'The work is organised around business rules and software ownership—not a queue of disconnected feature requests.' }}</p>@if($cmsPage->statistics->isNotEmpty())<div class="stats-grid">@foreach($cmsPage->statistics as $item)<div><strong data-counter>{{ $item->value }}</strong><span>{{ $item->title }}</span></div>@endforeach</div>@endif</div><div class="col-lg-7"><div class="why-list">@foreach($whyItems as $item)<article data-reveal><span>{{ str_pad($loop->iteration, 2, '0', STR_PAD_LEFT) }}</span><div><h3>{{ $item->title }}</h3><p>{{ $item->description }}</p></div></article>@endforeach</div></div></div></div></section>

@if($home->industries_enabled ?? true)<section class="page-section home-industries"><div class="container"><div class="section-heading"><div><p class="eyebrow">{{ $home->industries_label ?: 'Industries we serve' }}</p><h2>{{ $home->industries_title ?: 'Operations with real rules, roles, and consequences.' }}</h2><p>{{ $home->industries_description ?: 'Our strongest fit is where software coordinates people, transactions, inventory, service delivery, or management reporting.' }}</p></div></div><div class="industry-strip">@foreach($industryItems as $item)<article><i class="bi bi-{{ $item->icon ?: 'circle' }}"></i><h3>{{ $item->title }}</h3><p>{{ $item->description }}</p></article>@endforeach</div></div></section>@endif
@if($home->process_enabled ?? true)<section class="page-section home-process"><div class="container"><div class="section-heading"><div><p class="eyebrow">{{ $home->process_label ?: 'Development process' }}</p><h2>{{ $home->process_title ?: 'From operating problem to maintainable product.' }}</h2><p>{{ $home->process_description ?: 'Each stage produces decisions and evidence that the next stage can rely on.' }}</p></div></div><ol class="home-process-list">@foreach($processItems as $item)<li><span>{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</span><h3>{{ $item->title }}</h3><p>{{ $item->description }}</p></li>@endforeach</ol></div></section>@endif
@if($home->technology_enabled ?? true)<section class="page-section home-technology"><div class="container"><div class="row g-5 align-items-center"><div class="col-lg-5"><p class="eyebrow">{{ $home->technology_label ?: 'Technology we use' }}</p><h2>{{ $home->technology_title ?: 'Conventional foundations. Deliberate intelligence.' }}</h2><p class="section-lead">{{ $home->technology_description ?: 'Laravel, PHP, relational data, accessible web interfaces, automated testing, and carefully bounded AI integrations form a stack that can be operated and extended.' }}</p></div><div class="col-lg-7"><div class="technology-principles">@foreach($technologyItems as $item)<article><strong>{{ $item->title }}</strong><span>{{ $item->description }}</span></article>@endforeach</div></div></div></div></section>@endif
@if($featuredPortfolio->isNotEmpty())<section class="page-section"><div class="container"><div class="section-heading" data-reveal><div><p class="eyebrow">{{ $home->portfolio_label ?: 'Proven delivery' }}</p><h2>{{ $cmsPage->home->portfolio_title }}</h2><p>{{ $cmsPage->home->portfolio_description }}</p></div><a class="section-link" href="{{ route('portfolio') }}">{{ $home->portfolio_link_text ?: 'See our work' }} <i class="bi bi-arrow-right"></i></a></div><div class="row g-4">@foreach($featuredPortfolio as $project)<div class="col-md-6 col-xl-4" data-reveal><x-portfolio-card :project="$project" /></div>@endforeach</div></div></section>@endif

@if($home->faq_enabled ?? true)<section class="page-section home-faq"><div class="container col-xl-9"><div class="section-heading"><div><p class="eyebrow">{{ $home->faq_label ?: 'Frequently asked questions' }}</p><h2>{{ $home->faq_title ?: 'What business and technical teams usually ask first.' }}</h2></div></div><div class="accordion" id="home-faq">@foreach($faqItems as $item)<div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button @unless($loop->first) collapsed @endunless" type="button" data-bs-toggle="collapse" data-bs-target="#home-faq-{{ $loop->iteration }}" aria-expanded="{{ $loop->first ? 'true' : 'false' }}">{{ $item->title }}</button></h3><div id="home-faq-{{ $loop->iteration }}" class="accordion-collapse collapse @if($loop->first) show @endif" data-bs-parent="#home-faq"><div class="accordion-body">{{ $item->description }}</div></div></div>@endforeach</div></div></section>@endif
@if($latestPosts->isNotEmpty())<section class="page-section articles-section"><div class="container"><div class="section-heading" data-reveal><div><p class="eyebrow">{{ $home->articles_label ?: 'Knowledge center' }}</p><h2>{{ $cmsPage->home->articles_title }}</h2><p>{{ $cmsPage->home->articles_description }}</p></div><a class="section-link" href="{{ route('blog') }}">{{ $home->articles_link_text ?: 'Read all articles' }} <i class="bi bi-arrow-right"></i></a></div><div class="row g-4">@foreach(($featuredPosts->isNotEmpty()?$featuredPosts:$latestPosts->take(3)) as $post)<div class="col-md-6 col-xl-4" data-reveal><x-blog-card :post="$post"/></div>@endforeach</div></div></section>@endif

@if(($home->ecosystem_enabled ?? true) && $platforms->isNotEmpty())<section class="page-section ecosystem-section"><div class="container"><div class="section-heading" data-reveal><div><p class="eyebrow">{{ $home->ecosystem_label }}</p><h2>{{ $home->ecosystem_title }}</h2><p>{{ $home->ecosystem_description }}</p></div></div><div class="ecosystem-grid">@foreach($platforms as $platform)<article class="ecosystem-card" data-reveal @if($platform->brand_color)style="--platform-color: {{ $platform->brand_color }}"@endif><div class="ecosystem-logo">@if($platform->logo)<img src="{{ Storage::url($platform->logo) }}" alt="{{ $platform->name }} logo" loading="lazy">@else<span>{{ Str::of($platform->name)->substr(0,1)->upper() }}</span>@endif</div><div class="ecosystem-copy">@if($platform->badge)<span class="ecosystem-badge">{{ $platform->badge }}</span>@endif<h3>{{ $platform->name }}</h3><p>{{ $platform->description }}</p></div><a class="card-link" href="{{ $platform->website_url }}" @if($platform->open_in_new_tab)target="_blank" rel="noopener noreferrer"@endif>Visit Website <i class="bi bi-arrow-up-right" aria-hidden="true"></i></a></article>@endforeach</div><p class="ecosystem-note">{{ $home->ecosystem_note }}</p></div></section>@endif
@endsection


