@extends('installer.layout')
@php($step=7)
@section('title','Install')
@section('content')
<section class="installer-card" id="review"><div class="installer-card-header"><span class="step-label">Step 7 of 8</span><h1 class="h3 mt-2 mb-2">Ready to install</h1><p class="text-secondary mb-0">Review the destination before the installer creates the application.</p></div><div class="installer-card-body"><div class="summary-row"><span>Application</span><strong>{{ $summary['application']['name'] }}</strong></div><div class="summary-row"><span>Application URL</span><strong>{{ $summary['application']['url'] }}</strong></div><div class="summary-row"><span>Database</span><strong>{{ $summary['database']['database'] }} on {{ $summary['database']['host'] }}:{{ $summary['database']['port'] }}</strong></div><div class="summary-row"><span>Administrator</span><strong>{{ $summary['administrator']['email'] }}</strong></div><div class="summary-row"><span>Demo content</span><strong>{{ $summary['demo']['install_demo']?'Included':'Not included' }}</strong></div></div><div class="installer-card-footer"><a class="btn btn-link text-secondary text-decoration-none" href="{{ route('install.demo') }}">Back</a><button class="btn btn-primary px-4" id="install-button">Install DevNiox <i class="bi bi-play-fill ms-1"></i></button></div></section>
<section class="installer-card d-none" id="progress" aria-live="polite"><div class="installer-card-header"><span class="step-label">Installing</span><h1 class="h3 mt-2 mb-2">Preparing your application</h1><p class="text-secondary mb-0">Keep this window open until installation is complete.</p></div><div class="installer-card-body"><div class="install-log" id="install-log"></div></div></section>
<section class="installer-card d-none" id="complete"><div class="installer-card-header"><span class="step-label">Step 8 of 8</span><h1 class="h2 mt-2 mb-2"><i class="bi bi-check-circle-fill text-success me-2"></i>Installation successful</h1><p class="text-secondary mb-0">DevNiox is configured, optimized, and protected by its installation lock.</p></div><div class="installer-card-body"><div class="summary-row"><span>Administrator email</span><strong id="complete-email"></strong></div><p class="text-secondary mt-4 mb-0">The installer is now disabled. Use the administrator credentials you created to sign in.</p></div><div class="installer-card-footer"><a class="btn btn-outline-secondary" id="website-link" href="/">Open website</a><a class="btn btn-primary" id="login-link" href="/admin/login">Administrator login</a></div></section>
@endsection
@push('scripts')
<script>
const button=document.getElementById('install-button'),review=document.getElementById('review'),progress=document.getElementById('progress'),complete=document.getElementById('complete'),log=document.getElementById('install-log');
const add=(message,state='working')=>{const row=document.createElement('div');row.className='install-log-item';row.innerHTML='<i class="bi bi-'+(state==='error'?'x-circle-fill text-danger':'check-circle-fill text-success')+'"></i><span></span>';row.querySelector('span').textContent=message;log.appendChild(row)};
button.addEventListener('click',async()=>{button.disabled=true;review.classList.add('d-none');progress.classList.remove('d-none');add('Starting secure installation');
try{const response=await fetch(@json(route('install.run')),{method:'POST',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content,'Accept':'application/x-ndjson'}});
if(!response.ok)throw new Error('The installation request could not be started.');
const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';
while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const lines=buffer.split('\n');buffer=lines.pop();for(const line of lines){if(!line.trim())continue;const item=JSON.parse(line);if(item.type==='progress')add(item.message);if(item.type==='error')throw new Error(item.message);if(item.type==='complete'){progress.classList.add('d-none');complete.classList.remove('d-none');document.getElementById('complete-email').textContent=item.email;document.getElementById('login-link').href=item.login_url;document.getElementById('website-link').href=item.website_url;}}if(done)break;}
}catch(error){add(error.message,'error');const alert=document.createElement('div');alert.className='alert alert-danger mt-3 mb-0';alert.textContent=error.message;progress.querySelector('.installer-card-body').appendChild(alert);}});
</script>
@endpush
